<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Thông báo</title>
<meta http-equiv="content-language" content="en-us" />
</head>

<body>
<div align="center" style="margin-bottom:5%;margin-top:0%;">
    <div class="container text-center">
        <div class="content-404">
		<BR>
            <font color='red'><h2>WEBSITE ĐANG BẢO TRÌ!</h2></font>
			<font color='red'><h2>XIN VUI LÒNG QUAY LẠI SAU</h2></font>
        </div>
    </div>
</div>
</body>
</html>
