<?php include_once("mvc/model/shop.php");?>
<div class="single-product-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="product-bit-title">
                    <h2>
                        <div class="product-breadcroumb">
                           <?=$urlCategory;?>
						   <a class="active"><?=$productDetail[0]['PRODUCT']['PRODUCT_NAME'];?></a>
                        </div>
                    </h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="single-product-area">
    <div class="container">
        <div class="row">
            <div class="col-md-9 col-sm-12">
                <div class="single_left">
                    <div class="grid images_3_of_2">
                        <ul id="etalage">
							<?php
								$img=split('@@@',$productDetail[0]['PRODUCT']['SMALL_IMAGE_URL']);
								if(count($img>0)){
								unset($img[0]);
								if(count($arrayImage)>0)
									$img=$arrayImage;
								foreach($img as $k=>$image){
							?>
                            <li>
									<img class="etalage_thumb_image" src="/public/product/<?=$productDetail[0]['PRODUCT']['PRODUCT_ID'];?>/medium/<?=$image;?>" class="img-responsive" alt="">
                                    <a href="/public/product/<?=$productDetail[0]['PRODUCT']['PRODUCT_ID'];?>/medium/<?=$image;?>" title="<?=mb_strtoupper($productDetail[0]['PRODUCT']['PRODUCT_NAME'],'utf-8');?>">
									<img class="etalage_source_image" src="/public/product/<?=$productDetail[0]['PRODUCT']['PRODUCT_ID'];?>/medium/<?=$image;?>" class="img-responsive" title=""/>
									</a>
                            </li>
							<?php }}?>
                        </ul>
						<!--<div><button class="button-prev button1">Previous</button><button class="button-next button1">Next</button></div>-->
                        <div class="clearfix"></div>
                    </div>
                    <div class="desc1 span_3_of_2">
                        <h3><?=mb_strtoupper($productDetail[0]['PRODUCT']['PRODUCT_NAME'],'utf-8');?></h3>
                        <!--<span class="brand">Thương hiệu: <a href="#">NHT </a></span>-->
                        <span class="code">Mã sản phẩm: <pid><?=$productDetail[0]['PRODUCT']['MANUFACTURER_PARTY_ID'];?></pid></span>
                        <?=($productDetail[0]['PRODUCT']['DESCRIPTION']!='')?'<div class="line"></div><p>'.$productDetail[0]['PRODUCT']['DESCRIPTION'].'</p>':'';?>
                        <div class="line"></div>
                        <div id="price" class="price">
							<?php if($priceSale>0){?>
												<span class="price-new"><?=number_format($priceSale);?> VNĐ</span><br>
												<span class="price-old"><?=number_format($priceDefault);?> VNĐ</span>
											<?php }else{?>
												<span class="price-new"><?=number_format($priceDefault);?> VNĐ</span>
											<?php }?>
                            <!--<span class="price-tax">Ex Tax: $90.00</span><br>
                            <span class="points"><small>Price in reward points: 400</small></span><br>-->
                        </div>
                        <div class="line"></div>
						
                        <span class="text">Tình trạng : </span>
                        <span class="product-status">Còn hàng</span>
						<?php if(count($arrayFeature['listFeatureType'])>0){?>
                        <div class="line"></div>
                        <div class="det_nav1">
							<?php foreach($arrayFeature['listFeatureType'] as $k=>$featureType){?>
                            <h4>CHỌN <?=$featureType['DESCRIPTION_FEATURE_TYPE'];?></h4>
							<div class="clearfix"></div>
                            <div class=" sky-form col col-4">
								<select onchange="getProductFeature();" id="<?=$featureType['PRODUCT_FEATURE_TYPE_ID'];?>" class="dropdownlist wide">
								<?php $firt=1; foreach($arrayFeature['listFeature'][$k] as $k1=>$feature){
									$t=0;
									$t=$firt;
									if($select==$feature['PRODUCT_FEATURE_ID']){
								?>
									<option selected <?php if(in_array($featureType['PRODUCT_FEATURE_TYPE_ID'],$TYPE_SHOW_IMAGE)){$showImg=$t;?>findShow="<?=($k1==0)?1:$t;?>" <?php }?> value="<?=$feature['PRODUCT_FEATURE_ID'];?>"><?=$feature['DESCRIPTION_FEATURE'];?></option>
								<?php }else{?>
									<option <?php if(in_array($featureType['PRODUCT_FEATURE_TYPE_ID'],$TYPE_SHOW_IMAGE)){?>findShow="<?=($k1==0)?1:$t;?>" <?php }?> value="<?=$feature['PRODUCT_FEATURE_ID'];?>"><?=$feature['DESCRIPTION_FEATURE'];?></option>
								<?php }
									$firt=coutImage($productJunior,$feature['PRODUCT_FEATURE_ID'])+$t;
								}?>
							</select>
							<div class="clearfix"></div>
                            </div>
							<?php }?>
                        </div>
						<?php }?>
						
                        <div class="line"></div>
                        <div class="btn_form quantity-buy-detail">
                            <span class="txtcssQt">Số lượng</span> <input type="number" size="4" class="input-text qty text" title="Qty" value="1"
                                            min="0" step="1">
                            <a title="Thêm vào giỏ hàng" class="add-to-cart" href="#"><i class="fa fa-shopping-cart"></i>Thêm vào giỏ
                                hàng</a>
                            <a title="Mua sản phẩm" class="buy-now" href="checkout.html"><i class="fa fa-check"></i>Mua ngay</a>
                        </div>

                    </div>
					
                    <div class="clearfix"></div>
                </div>
                <div class="single-bottom1">
                    <h6>Chi tiết</h6>

                    <p class="prod-desc"> ✓ Balô dây rút hàng Việt Nam xuất khẩu, chất lượng đảm bảo.<br>
                        ✓ Chất liệu simili 100% không thấm nước, không bong tróc. Bạn sẽ yên tâm đi mưa & dễ lau chùi
                        khi bị bẩn.<br>
                        ✓ Công nghệ in Nhật Bản cho hình in đẹp, đặc biệt mặt in còn được phủ lên lớp màng chống trầy
                        xước và phai màu nên bạn hoàn toàn yên tâm khi sử dụng.</p>
                </div>
                <div class="single-bottom2">
                    <h6>Related Products</h6>

                    <div class="product">
                        <div class="product-desc">
                            <div class="product-img">
                                <img src="/template/img/w8.jpg" class="img-responsive " alt=""/>
                            </div>
                            <div class="prod1-desc">
                                <h5><a class="cbp-vm-title" href="#">Excepteur sint</a></h5>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="product_price">
                            <span class="price-access"><ins>150,000 VNĐ</ins></span>
                            <button class="button1"><span><i class="fa fa-shopping-cart"></i>Thêm vào giỏ hàng</span>
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="product">
                        <div class="product-desc">
                            <div class="product-img">
                                <img src="/template/img/w10.jpg" class="img-responsive " alt=""/>
                            </div>
                            <div class="prod1-desc">
                                <h5><a class="product_link" href="#">Excepteur sint</a></h5>

                                <p class="product_descr"> Vivamus ante lorem, eleifend nec interdum non, ullamcorper et
                                    arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
                                    inceptos himenaeos. </p>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="product_price">
								<span class="price-access">
										<ins>150,000 VNĐ</ins>
										<del>300,000 VNĐ</del>
								</span>
                            <button class="button1"><span><i class="fa fa-shopping-cart"></i>Thêm vào giỏ hàng</span>
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
					<div class="product">
                        <div class="product-desc">
                            <div class="product-img">
                                <img src="/template/img/w10.jpg" class="img-responsive " alt=""/>
                            </div>
                            <div class="prod1-desc">
                                <h5><a class="product_link" href="#">Excepteur sint</a></h5>

                                <p class="product_descr"> Vivamus ante lorem, eleifend nec interdum non, ullamcorper et
                                    arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
                                    inceptos himenaeos. </p>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="product_price">
								<span class="price-access">
										<ins>150,000 VNĐ</ins>
										<del>300,000 VNĐ</del>
								</span>
                            <button class="button1"><span><i class="fa fa-shopping-cart"></i>Thêm vào giỏ hàng</span>
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
					<div class="product">
                        <div class="product-desc">
                            <div class="product-img">
                                <img src="/template/img/w10.jpg" class="img-responsive " alt=""/>
                            </div>
                            <div class="prod1-desc">
                                <h5><a class="product_link" href="#">Excepteur sint</a></h5>

                                <p class="product_descr"> Vivamus ante lorem, eleifend nec interdum non, ullamcorper et
                                    arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
                                    inceptos himenaeos. </p>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="product_price">
								<span class="price-access">
										<ins>150,000 VNĐ</ins>
										<del>300,000 VNĐ</del>
								</span>
                            <button class="button1"><span><i class="fa fa-shopping-cart"></i>Thêm vào giỏ hàng</span>
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
					<div class="product">
                        <div class="product-desc">
                            <div class="product-img">
                                <img src="/template/img/w10.jpg" class="img-responsive " alt=""/>
                            </div>
                            <div class="prod1-desc">
                                <h5><a class="product_link" href="#">Excepteur sint</a></h5>

                                <p class="product_descr"> Vivamus ante lorem, eleifend nec interdum non, ullamcorper et
                                    arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
                                    inceptos himenaeos. </p>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="product_price">
								<span class="price-access">
										<ins>150,000 VNĐ</ins>
										<del>300,000 VNĐ</del>
								</span>
                            <button class="button1"><span><i class="fa fa-shopping-cart"></i>Thêm vào giỏ hàng</span>
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-12">
                <div class="w_sidebar">
                    <div class="w_nav1">
                        <h4><a href="shop.html">Tất cả</a></h4>
                        <div id="cssmenu">
							<?php echo $category;?>
						</div>
                    </div>
                    <h3>Lọc theo</h3>
                    <section class="sky-form">
                        <h4>Danh mục</h4>

                        <div class="row1 scroll-pane scrollbox3">
                            <div class="col col-4">
                                <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>kurtas</label>
                            </div>
                            <div class="col col-4">
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>kutis</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>churidar
                                    kurta</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>salwar</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>printed
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                            </div>
                        </div>
                    </section>
                    <section class="sky-form">
                        <h4>Phong cách</h4>

                        <div class="row1 scroll-pane scrollbox3">
                            <div class="col col-4">
                                <label class="checkbox"><input type="checkbox" name="checkbox"
                                                               checked=""><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                            </div>
                            <div class="col col-4">
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>vishud</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>amari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                            </div>
                        </div>
                    </section>
                    <section class="sky-form">
                        <h4>Màu sắc</h4>
                        <ul class="w_nav2 scrollbox3">
                            <li><a class="color1" href="#"></a></li>
                            <li><a class="color2" href="#"></a></li>
                            <li><a class="color3" href="#"></a></li>
                            <li><a class="color4" href="#"></a></li>
                            <li><a class="color5" href="#"></a></li>
                            <li><a class="color6" href="#"></a></li>
                            <li><a class="color7" href="#"></a></li>
                            <li><a class="color8" href="#"></a></li>
                            <li><a class="color9" href="#"></a></li>
                            <li><a class="color10" href="#"></a></li>
                            <li><a class="color12" href="#"></a></li>
                            <li><a class="color13" href="#"></a></li>
                            <li><a class="color14" href="#"></a></li>
                            <li><a class="color15" href="#"></a></li>
                            <li><a class="color5" href="#"></a></li>
                            <li><a class="color6" href="#"></a></li>
                            <li><a class="color7" href="#"></a></li>
                            <li><a class="color8" href="#"></a></li>
                            <li><a class="color9" href="#"></a></li>
                            <li><a class="color10" href="#"></a></li>
                        </ul>
                    </section>
                    <section class="sky-form">
                        <h4>Giảm giá</h4>

                        <div class="row1 scroll-pane scrollbox3">
                            <div class="col col-4">
                                <label class="radio"><input type="radio" name="radio" checked=""><i></i>60 % and
                                    above</label>
                                <label class="radio"><input type="radio" name="radio"><i></i>50 % and above</label>
                                <label class="radio"><input type="radio" name="radio"><i></i>40 % and above</label>
                            </div>
                            <div class="col col-4">
                                <label class="radio"><input type="radio" name="radio"><i></i>30 % and above</label>
                                <label class="radio"><input type="radio" name="radio"><i></i>20 % and above</label>
                                <label class="radio"><input type="radio" name="radio"><i></i>10 % and above</label>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>