<div class="single-product-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="product-bit-title">
                    <h2>
                        <div class="product-breadcroumb">
                            <?=$urlCategory;?>
                        </div>
                    </h2>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="single-product-area">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-3">
                <div class="w_sidebar">
                    <div class="w_nav1">
						<h4><a href="shop.html">Tất cả</a></h4>
                        <div id="cssmenu">
							<?php echo $category;?>
						</div>
                    </div>
                    <h3>Lọc theo</h3>
                    <section class="sky-form">
                        <h4>Danh mục</h4>

                        <div class="row1 scroll-pane scrollbox3">
                            <div class="col col-4">
                                <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>kurtas</label>
                            </div>
                            <div class="col col-4">
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>kutis</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>churidar
                                    kurta</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>salwar</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>printed
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                            </div>
                        </div>
                    </section>
                    <section class="sky-form">
                        <h4>Phong cách</h4>

                        <div class="row1 scroll-pane scrollbox3">
                            <div class="col col-4">
                                <label class="checkbox"><input type="checkbox" name="checkbox"
                                                               checked=""><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                            </div>
                            <div class="col col-4">
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>vishud</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>amari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                            </div>
                        </div>
                    </section>
                    <section class="sky-form">
                        <h4>màu sắc</h4>
                        <ul class="w_nav2 scrollbox3">
                            <li><a class="color1" href="#"></a></li>
                            <li><a class="color2" href="#"></a></li>
                            <li><a class="color3" href="#"></a></li>
                            <li><a class="color4" href="#"></a></li>
                            <li><a class="color5" href="#"></a></li>
                            <li><a class="color6" href="#"></a></li>
                            <li><a class="color7" href="#"></a></li>
                            <li><a class="color8" href="#"></a></li>
                            <li><a class="color9" href="#"></a></li>
                            <li><a class="color10" href="#"></a></li>
                            <li><a class="color12" href="#"></a></li>
                            <li><a class="color13" href="#"></a></li>
                            <li><a class="color14" href="#"></a></li>
                            <li><a class="color15" href="#"></a></li>
                            <li><a class="color5" href="#"></a></li>
                            <li><a class="color6" href="#"></a></li>
                            <li><a class="color7" href="#"></a></li>
                            <li><a class="color8" href="#"></a></li>
                            <li><a class="color9" href="#"></a></li>
                            <li><a class="color10" href="#"></a></li>
                        </ul>
                    </section>
                    <section class="sky-form">
                        <h4>giảm giá</h4>

                        <div class="row1 scroll-pane scrollbox3">
                            <div class="col col-4">
                                <label class="radio"><input type="radio" name="radio" checked=""><i></i>60 % and
                                    above</label>
                                <label class="radio"><input type="radio" name="radio"><i></i>50 % and above</label>
                                <label class="radio"><input type="radio" name="radio"><i></i>40 % and above</label>
                            </div>
                            <div class="col col-4">
                                <label class="radio"><input type="radio" name="radio"><i></i>30 % and above</label>
                                <label class="radio"><input type="radio" name="radio"><i></i>20 % and above</label>
                                <label class="radio"><input type="radio" name="radio"><i></i>10 % and above</label>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
			
            <div class="col-md-9 col-sm-9">
				<?php if(count($listProduct)>0){
					$delay=0.0;
				?>
                <div id="cbp-vm" class="cbp-vm-switcher cbp-vm-view-grid">
                    <div class="cbp-vm-options"><span>Xem theo</span>
                        <a id="grid" href="#" class="cbp-vm-icon cbp-vm-grid" data-view="cbp-vm-view-grid">Grid View</a>
                        <a id="list" href="#" class="cbp-vm-icon cbp-vm-list" data-view="cbp-vm-view-list">List View</a>

                        <div class="sort">Sắp xếp <select>
                                <option value="DEFAULT" selected="selected">Mặc định</option>
                                <option value="SORT_NAME_DECREASE">Tên A-Z</option>
                                <option value="SORT_NAME_INCREASE">Tên Z-A</option>
                                <option value="SORT_PRICE_INCREASE">Giá tăng dần</option>
                                <option value="SORT_PRICE_DECREASE">Giá giảm dần</option>
                            </select></div>
                    </div>

                    <div class="line_product"></div>
                    <div class="clearfix"></div>
					
                    <ul>
						<?php foreach($listProduct as $k=>$product){
							$img=split('@@@',$product['SMALL_IMAGE_URL']);
							$imgName='';
							if(count($img>0))
								$imgName=$img[1];
						?>
                        <li class="wow fadeIn animated" data-wow-delay="<?=$delay;?>s">
                            <div class="cbp-vm-image"><a title="<?=$product['PRODUCT_NAME'];?>" href="<?=$product['URL'];?>/<?=convertStringAndId($product['PRODUCT_NAME'],$product['PRODUCT_ID'],'.html');?>">
							<img src="/public/product/<?=$product['PRODUCT_ID'];?>/medium/<?=$imgName;?>" alt="<?=$product['PRODUCT_NAME'];?>"></a>
                            </div>
                            <div></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a title="<?=$product['PRODUCT_NAME'];?>" href="<?=$product['URL'];?>/<?=convertStringAndId($product['PRODUCT_NAME'],$product['PRODUCT_ID'],'.html');?>"><?=cut_string($product['PRODUCT_NAME'],18);?></a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                   <?php if($product['PRODUCT_PRICE_S']>0){?>
												<ins><?=number_format($product['PRODUCT_PRICE_S']);?> VNĐ</ins>
												<del><?=number_format($product['PRODUCT_PRICE_D']);?> VNĐ</del>
											<?php }else{?>
												<ins><?=number_format($product['PRODUCT_PRICE_D']);?> VNĐ</ins>
											<?php }?>
                                </div>
                                <div class="clearfix"></div>

                                <div class="clearfix"></div>
                                <div><a class="cbp-vm-icon cbp-vm-add item_add" href="#">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
                            <div class="lineListView"></div>
                        </li>
						<?php $delay=$delay+0.1;}?>
                    </ul>
                </div>
				<?php }else {echo "Danh mục đang cập nhật sản phẩm";}?>
				<?php if(count($listProduct)>0){?>
                <div class="row">
                    <div class="col-md-12">
                        <div class="product-pagination text-center">
                            <nav>
                                <ul class="pagination">
                                    <li>
                                        <a href="#" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    </li>
                                    <li><a href="#">1</a></li>
                                    <li><a href="#">2</a></li>
                                    <li><a href="#">3</a></li>
                                    <li><a href="#">4</a></li>
                                    <li><a href="#">5</a></li>
                                    <li>
                                        <a href="#" aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
				<?php }?>
            </div>
        </div>
    </div>
</div>