<div>
    <script type="text/javascript">
        $(function () {
            String.prototype.stripSlashes = function () {
                return this.replace(/\\(.)/mg, "$1");
            }
            document.title = 'Chi tiết sản phẩm';
            $('#titleProduct').puimegamenu();
            $('#txtProductEdit').puiinputtext();
            $('#txtProductName').puiinputtext();
            $('#txtDescription').puiinputtext();
            $('#txtProductPrice').puiinputtext();
            $('#pnlImage').puipanel();
            $('#update').puibutton({icon:'fa-save'});
            $('#updateSupplier').puibutton({
				icon:'fa-save',
				click: function () {
							var select = $('#drpSupplier').puidropdown('getSelectedValue');
							if(select!=0){
								$.ajax({
									type: "GET",
									url: 'ajax-action/product/update-product-supplier.php?idProduct=' + window.location.href.split('id=')[1]+'&supplier='+select,
									dataType: "json",
									context: this,
									success: function (response) {
										addMessage([{
                                                    severity: 'info',
                                                    summary: '',
                                                    detail: 'Cập nhật nhà cung cấp thành công'
                                                }]);
									}
								});
							}else{
								addMessage([{
                                                    severity: 'error',
                                                    summary: '',
                                                    detail: 'Vui lòng chọn nhà cung cấp'
                                                }]);
							}
				}
			});
            $('#refreshFeature').puibutton({
				icon:'fa-refresh',
				click: function () {
					$('#productFeature').puidropdown('removeAllOptions');
							$.ajax({
								type: "GET",
								url: 'ajax-action/product/list-product-feature.php?idProduct=' + window.location.href.split('id=')[1],
								dataType: "json",
								context: this,
								success: function (response) {
									$.each(response, function(key,value){
										$('#productFeature').puidropdown('addOption',value.label,value.value);
									});
								}
					});
						$.ajax({
                type: "GET",
                url: 'ajax-action/product/product-detail.php?id=' + id,
                dataType: "json",
                context: this,
                success: function (data) {
                    var arrayImageFeature = Array();
					if(data.length>0){
						var arrayImage = data[0].SMALL_IMAGE_URL.split('@@@');
						arrayImage.splice(0, 1);
					}
                    $.each(arrayImage, function (key, value) {
                        var temp = {imageName: value};
                        arrayImageFeature.push(temp);
                    });
					
                    $('#tblImageFeature').puidatatable({
                        emptyMessage: 'Không có danh sách hình ảnh',
                        columns: [
                            {
                                field: 'imageName', headerText: 'Hình ảnh', content: function (image) {
                                return $('<img src="../../../../public/product/' + id + '/thumbnail/' + image.imageName + '">');
                            }
                            }
                        ],
                        footer: 'Thêm ảnh bằng cách nhấn chuột phải -> [Thêm ảnh]',
                        selectionMode: 'single',
                        datasource: arrayImageFeature
                    });
                }
            });
                }
			});
            $('#addPrice').puibutton({
                click: function () {
                    $('#dlgAddProductPrice').puidialog('show');
                }
            });
            $('#contentUpload').load('upload/index.html');
            $('#title-product-detal').html('CHI TIẾT SẢN PHẨM ' + window.location.href.split('id=')[1]);
            var id = window.location.href.split('id=')[1];
            var func1 = $.ajax({
                type: "GET",
                url: 'ajax-action/product/product-detail.php?id=' + id,
                dataType: "json",
                context: this,
                cache: false
                //success: function (data) {
                //$('#drpCategoryEdit').puidropdown('selectValue', data[0].PRODUCT_CATEGORY_ID);
                //}
            });
			
			var func3 = $.ajax({
                type: "GET",
                url: 'ajax-action/supplier/supplier-list.php',
                dataType: "json",
                context: this,
            });
            var func2 = $.ajax({
                type: "GET",
                url: 'ajax-action/category/list-category.php',
                dataType: "json",
                context: this,
            });
            $.when(func1, func2,func3).done(function (r1, r2,r3) {
                $('#drpCategoryEdit').puidropdown({
					filter: true,
                    appendTo: 'self',
                    data: r2[0]
                });
				$('#drpSupplier').puidropdown({
					filter: true,
					appendTo: 'self',
                    data: r3[0]
                });
                $('#drpCategoryEdit').puidropdown('selectValue', r1[0][0].PRODUCT_CATEGORY_ID);
				//alert(r1[0][0].SUPPLIER);
				if(r1[0][0].SUPPLIER!=null&&r1[0][0].SUPPLIER!=''){
					$('#drpSupplier').puidropdown('selectValue', r1[0][0].SUPPLIER);
					$('#infor').remove();
					$.ajax({
								type: "GET",
								url: 'ajax-action/supplier/supplier-by-id.php?id=' + r1[0][0].SUPPLIER,
								dataType: "json",
								context: this,
								success: function (data) {
									$('#supplierInfo').append('<div id="infor"><div class="ui-grid-col-12" style="padding:2px 0px 0px 15px;line-height: 20px;"> <span style="color:red;">THÔNG TIN NHÀ CUNG CẤP</span><br> <span style="font-weight:700">Tên:</span> '+data[0].SUPPLIER_NAME+'<br><span style="font-weight:700">Email:</span> '+data[0].EMAIL+'<br><span style="font-weight:700">Điện thoại:</span> '+'0'+data[0].PHONE+'<br><span style="font-weight:700">Địa chỉ:</span> '+data[0].ADDRESS+'<br><span style="font-weight:700">Ghi chú:</span> '+data[0].COMMENT+'</div></div>');
								}
					});
				}else
					$('#drpSupplier').puidropdown('selectValue', 0);
                $('#txtProductEdit').val(r1[0][0].MANUFACTURER_PARTY_ID.stripSlashes());
                $('#txtProductName').val(r1[0][0].PRODUCT_NAME.stripSlashes());
                $('#txtDescription').val((r1[0][0].DESCRIPTION != '' || r1[0][0].DESCRIPTION != null) ? r1[0][0].DESCRIPTION.stripSlashes() : '');
                $('#txtLongDescription').val((r1[0][0].LONG_DESCRIPTION != '' || r1[0][0].LONG_DESCRIPTION != null) ? r1[0][0].LONG_DESCRIPTION.stripSlashes() : '');
                if (r1[0][0].IS_ACTIVE == 'Y') {
                    $('#chkPublicProduct').puitogglebutton('check');
                    $('#dlgPublicProduct').puidialog('hide');
                }
                $('#chkPublicProduct').puitogglebutton({
                    change: function (event, checked) {
                        $('#dlgPublicProduct').puidialog('show');
                    }
                });
				$('#drpSupplier').puidropdown({
					change: function (event) {
						var select = $('#drpSupplier').puidropdown('getSelectedValue');
						if(select!=0){
							$('#infor').remove();
							$.ajax({
								type: "GET",
								url: 'ajax-action/supplier/supplier-by-id.php?id=' + select,
								dataType: "json",
								context: this,
								success: function (data) {
									$('#supplierInfo').append('<div id="infor"><div class="ui-grid-col-12" style="padding:2px 0px 0px 15px;line-height: 20px;"> <span style="color:red;">THÔNG TIN NHÀ CUNG CẤP</span><br> <span style="font-weight:700">Tên:</span> '+data[0].SUPPLIER_NAME+'<br><span style="font-weight:700">Email:</span> '+data[0].EMAIL+'<br><span style="font-weight:700">Điện thoại:</span> '+'0'+data[0].PHONE+'<br><span style="font-weight:700">Địa chỉ:</span> '+data[0].ADDRESS+'<br><span style="font-weight:700">Ghi chú:</span> '+data[0].COMMENT+'</div></div>');
								}
							});
						}else{
							$('#infor').remove();
						}
					}
				});
                //CKEDITOR.replace('txtLongDescription');
            });
			
            $('#tabProductDetail').puitabview({
                effect: {
                    name: 'fade'
                    , duration: 'normal'
                },
            });


            $('#productFeature').puidropdown({
				filter: true,
                data: function (callback) {
                    $.ajax({
                        type: "GET",
                        url: 'ajax-action/product/list-product-feature.php?idProduct=' + window.location.href.split('id=')[1],
                        dataType: "json",
                        context: this,
                        success: function (response) {
                            callback.call(this, response);
                        }
                    });
                }
            });
            $('#productFeature').puidropdown({
                change: function (event) {
                    var select = $('#productFeature').puidropdown('getSelectedValue');
                    var data = $('#tblImageFeature').puidatatable('getContextMenuSelection');
                    //addMessage([{severity: 'info', summary: 'Row Selected', detail: (data.imageName)}]);
                    $.ajax({
                        type: "GET",
                        url: 'ajax-action/product/load-image-feature-to-product.php?idProduct=' + select,
                        dataType: "json",
                        context: this,
                        success: function (response) {
                            $('#tbllistImageFeatureProduct').puidatatable({
                                emptyMessage: 'Không có danh sách hình ảnh',
                                columns: [
                                    {
                                        field: 'imageName', headerText: 'Hình ảnh', content: function (image) {
                                        return $('<img src="../../../../public/product/' + id + '/thumbnail/' + image.imageName + '">');
                                    }
                                    }
                                ],
                                footer: 'Xóa ảnh bằng cách nhấn chuột phải -> [Xóa]',
                                selectionMode: 'single',
                                datasource: response
                            });
							$('#cmdelImage').remove();
							$('#cmImageFeature').remove();
							$('#contextMenuDiv').append('<ul id="cmdelImage"><li><a data-icon="fa-plus" onclick="ContextMenuDemo.delImage()">Xóa</a></li></ul>');
							$('#contextMenuDiv').append('<ul id="cmImageFeature"><li><a data-icon="fa-plus" onclick="ContextMenuDemo.addImageFeature()">Thêm ảnh</a></li></ul>');
                            $('#cmdelImage').puicontextmenu({
                                target: $('#tbllistImageFeatureProduct')
                            });
                            $('#cmImageFeature').puicontextmenu({
                                target: $('#tblImageFeature')
                            });
                            window.ContextMenuDemo = {
                                addImageFeature: function () {
                                    var select = $('#productFeature').puidropdown('getSelectedValue');
                                    if (select != -1) {
                                        var data = $('#tblImageFeature').puidatatable('getContextMenuSelection');
                                        //addMessage([{severity: 'info', summary: 'Row Selected', detail: (data.imageName)}]);
                                        $.ajax({
                                            type: "GET",
                                            url: 'ajax-action/product/add-image-feature-to-product.php?idProduct=' + select + '&image=' + data.imageName,
                                            dataType: "json",
                                            context: this,
                                            success: function (response) {
                                                if (response.error == 1) {
                                                    addMessage([{severity: 'error', summary: '', detail: 'Hình này đã tồn tại'}]);
                                                }else{
													$('#tbllistImageFeatureProduct').puidatatable({
														emptyMessage: 'Không có danh sách hình ảnh',
														columns: [
															{
																field: 'imageName', headerText: 'Hình ảnh', content: function (image) {
																return $('<img src="../../../../public/product/' + id + '/thumbnail/' + image.imageName + '">');
															}
															}
														],
														footer: 'Xóa ảnh bằng cách nhấn chuột phải -> [Xóa]',
														selectionMode: 'single',
														datasource: response
													});
													addMessage([{
                                                        severity: 'info',
                                                        summary: '',
                                                        detail: 'Thêm ảnh thành công'
                                                    }]);
												}
                                            }
                                        });
                                    } else {
                                        addMessage([{severity: 'warn', summary: '', detail: 'Chưa chọn tính năng'}]);
                                    }
                                },
                                delImage: function () {
                                    var select = $('#productFeature').puidropdown('getSelectedValue');
                                    if (select != -1) {
                                        var data = $('#tbllistImageFeatureProduct').puidatatable('getContextMenuSelection');
                                        $.ajax({
                                            type: "GET",
                                            url: 'ajax-action/product/delete-image-feature-to-product.php?idProduct=' + select + '&image=' + data.imageName,
                                            dataType: "json",
                                            context: this,
                                            success: function (response) {
                                                if (response.error == 1) {
                                                    addMessage([{severity: 'error', summary: '', detail: 'Hình này không tồn tại'}]);
                                                }else{
													$('#tbllistImageFeatureProduct').puidatatable({
														emptyMessage: 'Không có danh sách hình ảnh',
														columns: [
															{
																field: 'imageName', headerText: 'Hình ảnh', content: function (image) {
																return $('<img src="../../../../public/product/' + id + '/thumbnail/' + image.imageName + '">');
															}
															}
														],
														footer: 'Xóa ảnh bằng cách nhấn chuột phải -> [Xóa]',
														selectionMode: 'single',
														datasource: response
													});
													addMessage([{
                                                        severity: 'info',
                                                        summary: '',
                                                        detail: 'Xóa hình sản phẩm thành công'
                                                    }]);
												}
                                            }
                                        });
                                    }
                                }
                            };
                        }
                    });

                }
            });
			
            $.ajax({
                type: "GET",
                url: 'ajax-action/product/product-detail.php?id=' + id,
                dataType: "json",
                context: this,
                success: function (data) {
                    var arrayImageFeature = Array();
					if(data.length>0){
						var arrayImage = data[0].SMALL_IMAGE_URL.split('@@@');
						arrayImage.splice(0, 1);
					}
                    $.each(arrayImage, function (key, value) {
                        var temp = {imageName: value};
                        arrayImageFeature.push(temp);
                    });
                    $('#tblImageFeature').puidatatable({
                        emptyMessage: 'Không có danh sách hình ảnh',
                        columns: [
                            {
                                field: 'imageName', headerText: 'Hình ảnh', content: function (image) {
                                return $('<img src="../../../../public/product/' + id + '/thumbnail/' + image.imageName + '">');
                            }
                            }
                        ],
                        footer: 'Thêm ảnh bằng cách nhấn chuột phải -> [Thêm ảnh]',
                        selectionMode: 'single',
                        datasource: arrayImageFeature
                    });
                }
            });

            $('#dlgUpdate').puidialog({
                showEffect: 'fade',
                hideEffect: 'fade',
                minimizable: false,
                maximizable: false,
                responsive: true,
                minWidth: 200,
                modal: true,
                buttons: [{
                    text: 'Đóng',
                    icon: 'fa-close',
                    click: function () {
                        $('#dlgUpdate').puidialog('hide');
                    }
                },
                    {
                        text: 'Cập nhật',
                        icon: 'fa-save',
                        click: function () {
                            var manufacid = $('#txtProductEdit').val();
                            var productName = $('#txtProductName').val();
                            if (manufacid == null || manufacid == "") {
                                addMessage([{severity: 'warn', summary: '', detail: 'Phải nhập ký hiệu sản phẩm'}]);
                            } else if (productName == null || productName == "") {
                                addMessage([{severity: 'warn', summary: '', detail: 'Phải nhập tên sản phẩm'}]);
                            } else {
                                var _form = $('#frmProductInfor');
                                _form.unbind();
                                _form.submit(function (e) {
                                    for (instance in CKEDITOR.instances) {
                                        CKEDITOR.instances[instance].updateElement();
                                    }
                                    $('#loading').show();
                                    $('#dlgUpdate').block({
                                        message: null,
                                        overlayCSS: {backgroundColor: '#000', opacity: 0.3}
                                    });
                                    var postData = $(this).serializeArray();
                                    var formURL = $(this).attr("action");

                                    $.ajax(
                                        {
                                            url: formURL + '?id=' + id,
                                            type: "POST",
                                            data: postData,
                                            dataType: "json",
                                            success: function (data, textStatus, jqXHR) {
                                                $('#loading').hide();
                                                $('#dlgUpdate').unblock();
                                                if (data.mess == 2) {
                                                    addMessage([{
                                                        severity: 'error',
                                                        summary: '',
                                                        detail: 'Cập nhật sản phẩm thất bại'
                                                    }]);
                                                    $('#dlgUpdate').puidialog('hide');
                                                } else {
                                                    addMessage([{
                                                        severity: 'info',
                                                        summary: '',
                                                        detail: 'Cập nhật thông tin sản phẩm thành công'
                                                    }]);
                                                    $('#dlgUpdate').puidialog('hide');
                                                }

                                            },
                                            error: function (jqXHR, textStatus, errorThrown) {
                                                addMessage([{
                                                    severity: 'error',
                                                    summary: '',
                                                    detail: 'Lỗi cập nhật sản phẩm'
                                                }]);
                                                $('#loading').hide();
                                                $('#dlgUpdate').unblock();
                                                $('#dlgUpdate').puidialog('hide');
                                            }
                                        });
                                    e.preventDefault();	//STOP default action
                                    //e.unbind();
                                });
                                $("#frmProductInfor").submit(); //SUBMIT FORM
                            }

                        }
                    }
                ]
            });
            $('#update').puibutton({
                icon: 'fa-external-link-square',
                click: function () {
                    $('#dlgUpdate').puidialog('show');
                }
            });
            $('#mess').puigrowl();
            addMessage = function (msg) {
                $('#mess').puigrowl('show', msg);
            };

            $.ajax({
                type: "GET",
                url: 'ajax-action/product/list-all-feature-feature-type.php',
                dataType: "text",
                success: function (response) {
                    $('#multilistbox').html(response);
                }
            });
            

            $.ajax({
                type: "GET",
                url: 'ajax-action/product/load-feature-to-product.php?productId=' + window.location.href.split('id=')[1],
                dataType: "json",
                success: function (response) {
                    $.each(response['listFeatureType'], function (key, value) {
                        if ($('#tbFeature' + value.PRODUCT_FEATURE_TYPE_ID).length)
                            $('#tbFeature' + value.PRODUCT_FEATURE_TYPE_ID).remove();
                        if ($('#tbFeature' + value.PRODUCT_FEATURE_TYPE_ID).length == 0)
                            $('#tbFeatureAll').append("<div id='tbFeature" + value.PRODUCT_FEATURE_TYPE_ID + "' style='margin-bottom:5px;'></div>");
                        $('#tbFeature' + value.PRODUCT_FEATURE_TYPE_ID).puidatatable({
                            caption: value.DESCRIPTION_FEATURE_TYPE,
                            columns: [
                                {field: 'PRODUCT_FEATURE_ID', headerText: 'Mã tính năng'},
                                {field: 'DESCRIPTION_FEATURE', headerText: 'Mô tả'},
                                {
                                    field: 'PRODUCT_FEATURE_ID',
                                    headerText: '',
                                    content: function (car) {
                                        return $('<span onClick=delFeature("fearure","' + car.PRODUCT_FEATURE_ID + '@' + value.PRODUCT_FEATURE_TYPE_ID + '") style="text-decoration: underline;color:red;cursor: pointer;">Xóa</span>');
                                    }
                                }
                            ],
                            datasource: response['listFeature'][key]
                        });
                    });
                }
            });
            $('#btnAddFeature').puibutton({
                icon: 'fa-arrow-circle-right',
                iconPos: 'right',
                click: function (event) {
                    $('#loading').show();
                    $('#tabProductFeature').block({
                        message: null,
                        overlayCSS: {backgroundColor: '#000', opacity: 0.3}
                    });
                    var valSelect = $('input:hidden[name=product-feature-all]').val();
                    if (valSelect == '') {
                        addMessage([{
                            severity: 'error',
                            summary: '',
                            detail: 'Vui lòng chọn tính năng'
                        }]);
                    } else {
                        $.ajax({
                            type: "GET",
                            url: 'ajax-action/product/add-feature-to-product.php?value=' + valSelect + '&productId=' + id,
                            dataType: "json",
                            success: function (response) {
                                if (response.error == 1) {
                                    addMessage([{
                                        severity: 'error',
                                        summary: '',
                                        detail: 'Tính năng này đã tồn tại trong sản phẩm'
                                    }]);
                                } else {
                                    $('#btnSave').show();
                                    addMessage([{
                                        severity: 'info',
                                        summary: '',
                                        detail: 'Thêm tính năng thành công'
                                    }]);
                                    $.each(response['listFeatureType'], function (key, value) {
                                        if ($('#tbFeature' + value.PRODUCT_FEATURE_TYPE_ID).length)
                                            $('#tbFeature' + value.PRODUCT_FEATURE_TYPE_ID).remove();
                                        if ($('#tbFeature' + value.PRODUCT_FEATURE_TYPE_ID).length == 0)
                                            $('#tbFeatureAll').append("<div id='tbFeature" + value.PRODUCT_FEATURE_TYPE_ID + "' style='margin-bottom:5px;'></div>");
                                        $('#tbFeature' + value.PRODUCT_FEATURE_TYPE_ID).puidatatable({
                                            caption: value.DESCRIPTION_FEATURE_TYPE,
                                            columns: [
                                                {field: 'PRODUCT_FEATURE_ID', headerText: 'Mã tính năng'},
                                                {field: 'DESCRIPTION_FEATURE', headerText: 'Mô tả'},
                                                {
                                                    field: 'PRODUCT_FEATURE_ID',
                                                    headerText: '',
                                                    content: function (car) {
                                                        return $('<span onClick=delFeature("fearure","' + car.PRODUCT_FEATURE_ID + '@' + value.PRODUCT_FEATURE_TYPE_ID + '") style="text-decoration: underline;color:red;cursor: pointer;">Xóa</span>');
                                                    }
                                                }
                                            ],
                                            datasource: response['listFeature'][key]
                                        });
                                    });
                                }

                            }
                        });
                    }
                    $('#loading').hide();
                    $('#tabProductFeature').unblock();
                }
            });


            $('#tblProductPrice').puidatatable({
                emptyMessage: 'Không có danh sách giá sản phẩm',
                columns: [
                    {field: 'DESCRIPTION_PRICE_TYPE', headerText: 'Loại giá', bodyStyle: 'text-align:center;'},
                    {field: 'TERM_UOM_NAME', headerText: 'Tính năng', bodyStyle: 'text-align:center;'},
                    {field: 'PRICE', headerText: 'Giá', bodyStyle: 'text-align:center;'},
                    {field: 'CURRENCY_UOM_ID', headerText: 'Đơn vị', bodyStyle: 'text-align:center;'},
                    {field: 'FROM_DATE', headerText: 'Ngày thêm', bodyStyle: 'text-align:center;'},
                    {
                        field: 'PRODUCT_PRICE_TYPE_ID',
                        headerText: '',
                        bodyStyle: 'text-align:center;',
                        content: function (car) {
                            return $('<span title="Sửa" onClick=setValueUpdatePrice("' + id + '","' + car.PRODUCT_PRICE_TYPE_ID + '","' + car.TERM_UOM_ID + '","' + car.CURRENCY_UOM_ID + '","' + car.PRICE + '") style="color:red;text-decoration: underline;cursor: pointer;">Sửa</span> | <span title="Xóa" onClick=deletePrice("' + id + '","' + car.PRODUCT_PRICE_TYPE_ID + '","' + car.TERM_UOM_ID + '","' + car.CURRENCY_UOM_ID + '") style="color:red;text-decoration: underline;cursor: pointer;">Xóa</span>');
                        }
                    }
                ],
                datasource: function (callback) {
                    $.ajax({
                        type: "GET",
                        url: 'ajax-action/product-price/list-product-price.php?idProduct=' + window.location.href.split('id=')[1],
                        dataType: "json",
                        context: this,
                        success: function (response) {
                            callback.call(this, response);
                        }
                    });
                }
            });

            $('#listProductPriceType').puidropdown({
                data: function (callback) {
                    $.ajax({
                        type: "GET",
                        url: 'ajax-action/product-price-type/list-price-type.php',
                        dataType: "json",
                        context: this,
                        success: function (response) {
                            callback.call(this, response);
                        }
                    });
                }
            });

            $('#listProductFeature').puidropdown({
                data: function (callback) {
                    $.ajax({
                        type: "GET",
                        url: 'ajax-action/product/load-feature-to-product.php?listFeaturePrice=1&productId=' + window.location.href.split('id=')[1],
                        dataType: "json",
                        context: this,
                        success: function (response) {
                            callback.call(this, response);
                        }
                    });
                }
            });
            $('#listCurrencyUom').puidropdown();
            $('#dlgAddProductPrice').puidialog({
                showEffect: 'fade',
                hideEffect: 'fade',
                minimizable: false,
                maximizable: false,
                responsive: true,
                minWidth: 200,
                modal: true,
                buttons: [{
                    text: 'Đóng',
                    icon: 'fa-close',
                    click: function () {
                        $('#dlgAddProductPrice').puidialog('hide');
                    }
                },
                    {
                        text: 'Thêm',
                        icon: 'fa-plus',
                        click: function () {
                            var price = $('#txtProductPrice').val();
                            if (price == null || price == "") {
                                addMessage([{severity: 'warn', summary: '', detail: 'Chưa nhập giá sản phẩm'}]);
                            } else {
                                var _form = $('#frmAddPriceProduct');
                                _form.unbind();
                                _form.submit(function (e) {
                                    $('#loading').show();
                                    $('#dlgAddProductPrice').block({
                                        message: null,
                                        overlayCSS: {backgroundColor: '#000', opacity: 0.3}
                                    });
                                    var postData = $(this).serializeArray();
                                    var formURL = $(this).attr("action");
                                    $.ajax(
                                        {
                                            url: formURL + '?idProduct=' + id,
                                            type: "POST",
                                            data: postData,
                                            dataType: "json",
                                            success: function (data, textStatus, jqXHR) {
                                                $('#loading').hide();
                                                $('#dlgAddProductPrice').unblock();
                                                if (data.error == 1) {
                                                    addMessage([{
                                                        severity: 'error',
                                                        summary: '',
                                                        detail: 'Loại giá này đã tồn tại trong sản phẩm'
                                                    }]);
                                                } else {
                                                    $('#tblProductPrice').puidatatable('reload');
                                                    addMessage([{
                                                        severity: 'info',
                                                        summary: '',
                                                        detail: 'Thêm giá sản phẩm thành công'
                                                    }]);
                                                    //$('#listProductPriceType').puidropdown('selectValue', -1);
                                                    $('#listProductFeature').puidropdown('selectValue', -1);
                                                    $('#frmAddPriceProduct')[0].reset();
                                                }
                                            },
                                            error: function (jqXHR, textStatus, errorThrown) {
                                                addMessage([{
                                                    severity: 'error',
                                                    summary: '',
                                                    detail: 'Lỗi thêm giá sản phẩm'
                                                }]);
                                                $('#loading').hide();
                                                $('#dlgAddProductPrice').unblock();
                                            }
                                        });
                                    e.preventDefault();	//STOP default action
                                });
                                $("#frmAddPriceProduct").submit(); //SUBMIT FORM
                            }
                            $('#dlgAddProductPrice').puidialog('hide');
                        }
                    }
                ]
            });

            $('#chkPublicProduct').puitogglebutton({
                onLabel: 'Sản phẩm đã Hiển Thị',
                offLabel: 'Sản phẩm đang Ẩn',
                onIcon: 'fa-check-square',
                offIcon: 'fa-square'
            });
            $('#dlgPublicProduct').puidialog({
                showEffect: 'fade',
                hideEffect: 'fade',
                minimizable: false,
                maximizable: false,
                responsive: true,
                minWidth: 200,
                modal: true,
                buttons: [{
                    text: 'Hủy',
                    icon: 'fa-close',
                    click: function () {
                        $('#dlgPublicProduct').puidialog('hide');
                        var check = $('#chkPublicProduct').puitogglebutton('isChecked');
                        if (check == true)
                            $('#chkPublicProduct').puitogglebutton('uncheck');
                        else
                            $('#chkPublicProduct').puitogglebutton('check');
                    }
                },
                    {
                        text: 'Có',
                        icon: 'fa-trash',
                        click: function () {
                            $('#dlgPublicProduct').puidialog('hide');
                            $.ajax(
                                {
                                    url: 'ajax-action/product/public-product.php?idProduct=' + id,
                                    type: "GET",
                                    dataType: "json",
                                    success: function (data, textStatus, jqXHR) {
                                        $('#dlgPublicProduct').unblock();
                                        if (data.price == 1) {
                                            addMessage([{
                                                severity: 'error',
                                                summary: '',
                                                detail: 'Sản phẩm chưa được cập nhật giá'
                                            }]);
                                        } else {
                                            if (data.info == 1) {
                                                addMessage([{
                                                    severity: 'error',
                                                    summary: '',
                                                    detail: 'Sản phẩm chưa cập nhật đầy đủ thông tin'
                                                }]);
                                            } else {
                                                var check = $('#chkPublicProduct').puitogglebutton('isChecked');
                                                if (check == true)
                                                    addMessage([{
                                                        severity: 'info',
                                                        summary: '',
                                                        detail: 'Public sản phẩm thành công'
                                                    }]);
                                                else
                                                    addMessage([{
                                                        severity: 'info',
                                                        summary: '',
                                                        detail: 'UnPublic sản phẩm thành công'
                                                    }]);

                                            }
                                        }
                                        if (data.price == 1 || data.info == 1) {
                                            $('#chkPublicProduct').puitogglebutton('uncheck');
                                        }
                                    },
                                    error: function (jqXHR, textStatus, errorThrown) {
                                        addMessage([{
                                            severity: 'error',
                                            summary: '',
                                            detail: 'Lỗi public sản phẩm'
                                        }]);
                                        $('#dlgPublicProduct').unblock();
                                    }
                                });
                        }
                    }
                ]
            });
        });
		//-------format price--------------------------------------------------
            function AddDot(nStr) {
                nStr += '';
                x = nStr.split(',');
                x1 = x[0];
                x2 = x.length > 1 ? ',' + x[1] : '';
                var rgx = /(\d+)(\d{3})/;
                while (rgx.test(x1)) {
                    x1 = x1.replace(rgx, '$1' + ',' + '$2');
                }
                return x1 + x2;
            }

            function FormatPrice(el) {
                el.value = AddDot(el.value.replace(/[^\d]/g, ''));
            }
		function delFeature(type, value) {

                $('#dlgDelFeature').remove();
                $('#divDelFeature').append('<div id="dlgDelFeature" title="Thông báo"><p></p><p>Bạn có chắc muốn xóa tính năng?</p></div>');
                $('#dlgDelFeature').puidialog({
                    showEffect: 'fade',
                    hideEffect: 'fade',
                    minimizable: false,
                    maximizable: false,
                    responsive: true,
                    minWidth: 200,
                    modal: true,
                    buttons: [{
                        text: 'Đóng',
                        icon: 'fa-close',
                        click: function () {
                            $('#dlgDelFeature').puidialog('hide');
                        }
                    },
                        {
                            text: 'Xóa',
                            icon: 'fa-trash',
                            click: function () {
                                if (type == 'fearure') {
                                    var res = value.split("@");
                                    $('#tbFeature' + res[1]).remove();
                                } else {
                                    $('#tbFeature' + value).remove();
                                }
                                $.ajax({
                                    type: "GET",
                                    url: 'ajax-action/product/del-feature-product.php?type=' + type + '&value=' + value + '&productId=' + id,
                                    dataType: "json",
                                    success: function (response) {
										if(response.error==1){
												addMessage([{
												severity: 'error',
												summary: '',
												detail: 'Tính năng này đã sử dụng nên không được xóa'
											}]);

										}else{
											addMessage([{
												severity: 'info',
												summary: '',
												detail: 'Xóa tính năng thành công'
											}]);
										}
                                        $.each(response['listFeatureType'], function (key, value) {
                                            if ($('#tbFeature' + value.PRODUCT_FEATURE_TYPE_ID).length)
                                                $('#tbFeature' + value.PRODUCT_FEATURE_TYPE_ID).remove();
                                            if ($('#tbFeature' + value.PRODUCT_FEATURE_TYPE_ID).length == 0)
                                                $('#tbFeatureAll').append("<div id='tbFeature" + value.PRODUCT_FEATURE_TYPE_ID + "' style='margin-bottom:5px;'></div>");

                                            $('#tbFeature' + value.PRODUCT_FEATURE_TYPE_ID).puidatatable({
                                                caption: value.DESCRIPTION_FEATURE_TYPE,
                                                columns: [
                                                    {field: 'PRODUCT_FEATURE_ID', headerText: 'Mã tính năng'},
                                                    {field: 'DESCRIPTION_FEATURE', headerText: 'Mô tả'},
                                                    {
                                                        field: 'PRODUCT_FEATURE_ID',
                                                        headerText: '',
                                                        content: function (car) {
                                                            return $('<span onClick=delFeature("fearure","' + car.PRODUCT_FEATURE_ID + '@' + value.PRODUCT_FEATURE_TYPE_ID + '") style="text-decoration: underline;color:red;cursor: pointer;">Xóa</span>');
                                                        }
                                                    }
                                                ],
                                                datasource: response['listFeature'][key]
                                            });
                                        });
                                    }
                                });
                                $('#dlgDelFeature').puidialog('hide');
                            }
                        }
                    ]
                });
                $('#dlgDelFeature').puidialog('show');
            }
			function setValueUpdatePrice(productPriceId, productPriceTypeId, feature, currencyUomId, price) {
                $('#frmAddPriceProduct').block({
                    message: null,
                    overlayCSS: {backgroundColor: '#000', opacity: 0.3}
                });
                $('#action').val('edit');
                $('#editPriceDiv1').show();
                $('#editPriceDiv2').show();
                $('#addPriceDiv').hide();
                $('#listProductFeature').puidropdown('selectValue', feature);
                $('#listCurrencyUom').puidropdown('selectValue', currencyUomId);
                $('#listProductPriceType').puidropdown('selectValue', productPriceTypeId);
                $('#txtProductPrice').val(price);
                $('#editPrice').puibutton({
                    click: function (event) {
                        updatePrice(productPriceId, productPriceTypeId, feature, currencyUomId);
                    }
                });
                $('#resetPrice').puibutton({
                    click: function (event) {
                        $('#editPriceDiv1').hide();
                        $('#editPriceDiv2').hide();
                        $('#addPriceDiv').show();
                        $('#action').val('add');
                        $('#listProductFeature').puidropdown('selectValue', -1);
                        $('#frmAddPriceProduct')[0].reset();
                        $('#action').val('add');
                    }
                });
                $('#frmAddPriceProduct').unblock();
            }

            function deletePrice(productPriceId, productPriceTypeId, feature, currencyUomId) {
                $('#action').val('del');
                $('#dlgDelPrice').remove();
                $('#divDelPrice').append('<div id="dlgDelPrice" title="Thông báo"><p></p><p>Bạn có chắc muốn xóa giá sản phẩm?</p></div>');
                $('#dlgDelPrice').puidialog({
                    showEffect: 'fade',
                    hideEffect: 'fade',
                    minimizable: false,
                    maximizable: false,
                    responsive: true,
                    minWidth: 200,
                    modal: true,
                    buttons: [{
                        text: 'Hủy',
                        icon: 'fa-close',
                        click: function () {
                            $('#dlgDelPrice').puidialog('hide');
                            $('#editPriceDiv1').hide();
                            $('#editPriceDiv2').hide();
                            $('#addPriceDiv').show();
                            $('#action').val('add');
                            $('#listProductFeature').puidropdown('selectValue', -1);
                            $('#frmAddPriceProduct')[0].reset();
                            $('#action').val('add');
                        }
                    },
                        {
                            text: 'Có',
                            icon: 'fa-trash',
                            click: function () {
                                var check = $('#chkPublicProduct').puitogglebutton('isChecked');
                                if (check == false) {
                                    $.ajax(
                                        {
                                            url: 'ajax-action/product-price/update-product-price.php?action=del&idProduct=' + id + '&productPriceTypeId=' + productPriceTypeId + '&feature=' + feature + '&currencyUomId=' + currencyUomId,
                                            type: "GET",
                                            dataType: "json",
                                            success: function (data, textStatus, jqXHR) {
                                                $('#loading').hide();
                                                $('#dlgDelPrice').unblock();
                                                $('#tblProductPrice').puidatatable('reload');
                                                addMessage([{
                                                    severity: 'info',
                                                    summary: '',
                                                    detail: 'Xóa giá sản phẩm thành công'
                                                }]);
                                                $('#action').val('add');
                                                $('#listProductFeature').puidropdown('selectValue', -1);
                                                $('#frmAddPriceProduct')[0].reset();
                                            },
                                            error: function (jqXHR, textStatus, errorThrown) {
                                                addMessage([{
                                                    severity: 'error',
                                                    summary: '',
                                                    detail: 'Lỗi xóa giá sản phẩm'
                                                }]);
                                                $('#loading').hide();
                                                $('#dlgDelPrice').unblock();
                                            }
                                        });
                                    $('#dlgDelPrice').puidialog('hide');
                                } else {
                                    addMessage([{
                                        severity: 'error',
                                        summary: '',
                                        detail: 'Sản phẩm đang Public nên không thể xóa giá'
                                    }]);
                                }
                            }

                        }
                    ]
                });
                $('#dlgDelPrice').puidialog('show');
            }

            function updatePrice(productPriceId, productPriceTypeId, feature, currencyUomId) {
                $('#dlgUpdatePrice').remove();
                $('#divUpdatePrice').append('<div id="dlgUpdatePrice" title="Thông báo"><p></p><p>Bạn có chắc muốn cập nhật giá?</p></div>');
                $('#dlgUpdatePrice').puidialog({
                    showEffect: 'fade',
                    hideEffect: 'fade',
                    minimizable: false,
                    maximizable: false,
                    responsive: true,
                    minWidth: 200,
                    modal: true,
                    buttons: [{
                        text: 'Hủy',
                        icon: 'fa-close',
                        click: function () {
                            $('#dlgUpdatePrice').puidialog('hide');
                            $('#editPriceDiv1').hide();
                            $('#editPriceDiv2').hide();
                            $('#addPriceDiv').show();
                            $('#action').val('add');
                            $('#listProductFeature').puidropdown('selectValue', -1);
                            $('#frmAddPriceProduct')[0].reset();
                            $('#action').val('add');
                        }
                    },
                        {
                            text: 'Có',
                            icon: 'fa-save',
                            click: function () {
                                var price = $('#txtProductPrice').val();
                                if (price == null || price == "") {
                                    addMessage([{severity: 'warn', summary: '', detail: 'Chưa nhập giá sản phẩm'}]);
                                } else {
                                    var _form = $('#frmAddPriceProduct');
                                    _form.unbind();
                                    _form.submit(function (e) {
                                        $('#loading').show();
                                        $('#dlgUpdatePrice').block({
                                            message: null,
                                            overlayCSS: {backgroundColor: '#000', opacity: 0.3}
                                        });
                                        var postData = $(this).serializeArray();
                                        var formURL = $(this).attr("action");
                                        $.ajax(
                                            {
                                                url: formURL + '?idProduct=' + id + '&productPriceTypeId=' + productPriceTypeId + '&feature=' + feature + '&currencyUomId=' + currencyUomId,
                                                type: "POST",
                                                data: postData,
                                                dataType: "json",
                                                success: function (data, textStatus, jqXHR) {
                                                    $('#loading').hide();
                                                    $('#dlgUpdatePrice').unblock();
                                                    $('#tblProductPrice').puidatatable('reload');
                                                    addMessage([{
                                                        severity: 'info',
                                                        summary: '',
                                                        detail: 'Cập nhật giá sản phẩm thành công'
                                                    }]);
                                                    $('#action').val('add');
                                                    $('#listProductFeature').puidropdown('selectValue', -1);
                                                    $('#frmAddPriceProduct')[0].reset();
                                                },
                                                error: function (jqXHR, textStatus, errorThrown) {
                                                    addMessage([{
                                                        severity: 'error',
                                                        summary: '',
                                                        detail: 'Lỗi cập nhật giá sản phẩm'
                                                    }]);
                                                    $('#loading').hide();
                                                    $('#dlgUpdatePrice').unblock();
                                                }
                                            });
										$('#editPriceDiv1').hide();
										$('#editPriceDiv2').hide();
										$('#addPriceDiv').show();
                                        e.preventDefault();	//STOP default action
                                    });
                                    $("#frmAddPriceProduct").submit(); //SUBMIT FORM
                                }
                                $('#dlgUpdatePrice').puidialog('hide');
                            }
                        }
                    ]
                });
                $('#dlgUpdatePrice').puidialog('show');
            }
    </script>
    <script type="text/javascript">
        CKEDITOR.replace('txtLongDescription');
        CKEDITOR.config.width = "auto";
        CKEDITOR.config.height = 320;
        CKEDITOR.config.extraPlugins = 'confighelper';
        CKEDITOR.config.placeholder = 'Nhập mô tả chi tiết sản phẩm';
    </script>
    <style type="text/css">
        .ui-dropdown {
            width: 150px;
        }

        img#loading {
            position: absolute;
            display: none;
            top: 40%;
            right: 40%;
            z-index: 10000;
        }

        .ui-multiselectlistbox-listcontainer {
            margin-top: 5px;
            padding: 2px;
            width: 100%;
        }

        .ui-multiselectlistbox .ui-multiselectlistbox-item {
            padding: 8px;
            border: 0 none;
            cursor: pointer;
            font-weight: normal;
            font-size: 16px;
        }

        .ui-multiselectlistbox .ui-multiselectlistbox-header {
            text-align: center;
            padding: 10px 10px;
            border-bottom: 0px none;
            font-size: 16px;
        }
    </style>
    <div id="mess"/>
    <img id="loading" src='../../primeui/showcase/resources/images/loading.gif'/>

    <div class="ContentSideSections">
        <div id="titleProduct">
            <ul>
                <li style="width:20%;padding-top: 8px;font-size: 13px;font-weight:600;"><span
                        id="title-product-detal"></span></li>
                <li style="width:80%;padding-top: 3px;font-size: 13px;text-align:right"><input type="checkbox"
                                                                                               name="chkPublicProduct"
                                                                                               id="chkPublicProduct"
                                                                                               value="1"/></li>
				
                <ul>
        </div>
    </div>
    <div id="dlgUpdate" title="Thông báo">
        <p></p>

        <p>Bạn có chắc muốn cập nhật thông tin?</p>
    </div>
    <div id="dlgAddProductPrice" title="Thông báo">
        <p></p>

        <p>Bạn có chắc muốn thêm giá sản phẩm?</p>
    </div>
	<div id="contextMenuDiv"></div>
    <div id="divDelFeature"></div>
    <div id="divDelPrice"></div>
    <div id="dlgPublicProduct" title="Thông báo"><p></p>

        <p>Bạn có chắc muốn Hiển thị sản phẩm này?</p></div>
    <div id="divUpdatePrice"></div>
    <div class="ContentSideSections Implementation ui-fluid">
        <div id="tabProductDetail">
            <ul>
                <li><a href="#tabInforProduct">Thông tin sản phẩm</a></li>
                <li><a href="#tabProductFeature">Tính năng</a></li>
                <li><a href="#tabProductPrice">Giá sản phẩm</a></li>
                <li><a href="#tabProductImageFeature">Ảnh tính năng</a></li>
				<li><a href="#tabSupplierProduct">Nhà cung cấp</a></li>
            </ul>
            <div>
                <div id="tabInforProduct">
                    <div class="ui-grid ui-grid-responsive">
                        <form id="frmProductInfor" name="frmProductInfor" method="post"
                              action="ajax-action/product/update-product.php">
                            <div class="ui-grid-col-12">
                                <div class="ui-grid-row">
                                    <div class="ui-grid-col-1" style="padding-top:5px;font-weight: 700;">Danh mục</div>
                                    <div class="ui-grid-col-4"><select id="drpCategoryEdit"
                                                                       name="drpCategoryEdit"></select>
                                    </div>
                                    <div class="ui-grid-col-1" style="padding-left:15px;padding-top:5px;font-weight: 700;">Ký hiệu</div>
                                    <div class="ui-grid-col-6"><input id="txtProductEdit" name="txtProductEdit"
                                                                      type="text"
                                            /></div>
                                </div>
                                <div style="height:8px;"></div>
                                <div class="ui-grid-row">
                                    <div class="ui-grid-col-1" style="padding-top:5px;font-weight: 700;">Tên sản phẩm</div>
                                    <div class="ui-grid-col-11"><input id="txtProductName" name="txtProductName"
                                                                       type="text"
                                            /></div>
                                </div>
                                <div style="height:8px;"></div>
                                <div class="ui-grid-row">
                                    <div class="ui-grid-col-1" style="padding-top:5px;font-weight: 700;">Mô tả sản phẩm</div>
                                    <div class="ui-grid-col-11"><input id="txtDescription" name="txtDescription"
                                                                       type="text"
                                            /></div>
                                </div>
                                <div style="height:8px;"></div>
                                <div class="ui-grid-row">
                                    <div class="ui-grid-col-1" style="font-weight: 700;">Mô tả chi tiết</div>
                                    <div class="ui-grid-col-11"><textarea id="txtLongDescription"
                                                                          name="txtLongDescription"></textarea></div>
                                </div>
                                <div style="height:8px;margin-top:5px;margin-bottom:5px;"></div>
                                <div class="ui-grid-row">
                                    <div class="ui-grid-col-1"></div>
                                    <div class="ui-grid-col-11">
                                        <button type="button" id="update">Cập nhật</button>
                                    </div>
                                </div>
                                <div style="height:4px;margin-top:5px;"></div>
                            </div>
                        </form>
                        <div class="ui-grid-col-12">
                            <div class="ui-grid-row">
                                <div class="ui-grid-col-1" style="padding-top:5px"></div>
                                <div class="ui-grid-col-11">
                                    <div style="height:8px;"></div>
                                    <div id="pnlImage" title="Hình ảnh">
                                        <div id="contentUpload"></div>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>

                </div>
                <div id="tabProductFeature">
                    <div class="ui-grid ui-grid-responsive">
                        <div class="ui-grid-row">
                            <div class="ui-grid-col-4">
                                <div id="multilistbox"></div>
                                <button id="btnAddFeature" type="button" style="margin-top:10px">Thêm</button>
                            </div>
                            <div class="ui-grid-col-1">
                            </div>
                            <div class="ui-grid-col-7">
                                <div id="tbFeatureAll"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="tabProductPrice">
                    <div id="tblProductPrice"></div>
                    <form id="frmAddPriceProduct" name="frmAddPriceProduct" method="post"
                          action="ajax-action/product-price/update-product-price.php">
                        <input type="hidden" name="action" id="action" value="add"/>

                        <div class="ui-grid ui-grid-responsive">
                            <div class="ui-grid-row">
                                <div class="ui-state-default"
                                     style="padding:8px 5px 5px 14px;width:16.6%;text-align:center;">
                                    <select id="listProductPriceType" name="listProductPriceType"></select>
                                </div>
                                <div class="ui-state-default "
                                     style="padding:8px 5px 5px 20px;width:16.67%;text-align:center;">
                                    <select id="listProductFeature" name="listProductFeature"></select>
                                </div>
                                <div class="ui-state-default "
                                     style="padding:8px 5px 5px 20px;width:16.67%;text-align:center;"><input
                                        aria-disabled="false" aria-readonly="false" onkeyup="FormatPrice(this);"
                                        type="text" name="txtProductPrice" id="txtProductPrice"/></div>
                                <div class="ui-state-default "
                                     style="padding:8px 5px 5px 20px;width:16.67%;text-align:center;">
                                    <select id="listCurrencyUom" name="listCurrencyUom">
                                        <option value="VND">VNĐ</option>
                                    </select>
                                </div>
                                <div id="addPriceDiv" class="ui-state-default "
                                     style="padding:5px 5px 5px 20px;width:33.3%;text-align:center;">
                                    <button type="button" id="addPrice">Thêm</button>
                                </div>
                                <div id="editPriceDiv1" class="ui-state-default "
                                     style="display:none;padding:5px 5px 5px 20px;width:16.67%;text-align:center;">
                                    <button type="button" id="editPrice">Cập nhật</button>
                                </div>
                                <div id="editPriceDiv2" class="ui-state-default "
                                     style="display:none;padding:5px 5px 5px 20px;width:16.67%;text-align:center;">
                                    <button type="button" id="resetPrice">Hủy</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div id="tabProductImageFeature">
                    <div class="ui-grid ui-grid-responsive">
                        <div class="ui-grid-row">
                            <div class="ui-grid-col-4">
                                <div id="tblImageFeature"></div>
                            </div>
                            <div class="ui-grid-col-2"
                                 style="text-align:right;padding:3px 10px 3px 0px;font-size:12px;font-weight: 700;">
                                Danh sách tính năng
                            </div>
                            <div class="ui-grid-col-5">
                                <select name="productFeature" id="productFeature"></select>
                                <div id="tbllistImageFeatureProduct"></div>
                            </div>
							 <div class="ui-grid-col-1">
                               <button style="width:120px;" type="button" id="refreshFeature">Làm mới</button>
                            </div>
                        </div>
                    </div>
                </div>
				<div id="tabSupplierProduct" style="min-height:300px;">
                    <div class="ui-grid ui-grid-responsive">
                        <div class="ui-grid-row">
                            <div class="ui-grid-col-4">
								<select id="drpSupplier" name="drpSupplier">
									<option value="0" selected>-- Chọn nhà cung cấp --</option>
								</select>
                            </div>
                            <div class="ui-grid-col-2" style="padding:0;padding-left:5px;">
								<button type="button" id="updateSupplier" style="padding:0;">Cập nhật</button>
                            </div>
                            <div class="ui-grid-col-6" id="supplierInfo">
								
                            </div>
                        </div>
                    </div>
                </div>
				
            </div>
        </div>
    </div>
</div>
</div>

<script language="javascript">
    SyntaxHighlighter.highlight();
</script>

</div>