<div class="product-widget-area">
    <div class="container">
        <div class="check">
            <div class="col-md-9 cart-items">
                <h1>Giỏ hàng của bạn(2)</h1>

                <div class="cart-header">
                    <div class="close1"></div>
                    <div class="cart-sec simpleCart_shelfItem">
                        <div class="cart-item cyc">
                            <img src="/template/img/8.jpg" class="img-responsive" alt=""/>
                        </div>
                        <div class="cart-item-info">
                            <h3><a href="#">Mountain Hopper(XS R034)</a><span>Model No: 3578</span></h3>
                            <ul class="qty">
                                <li><p>Size : 5</p></li>
                                <li>
                                    <p>

                                    <div class="quantity buttons_added">Số lượng
                                        <input type="button" class="minus" value="-"/>
                                        <input type="number" size="4" class="input-text qty text" title="Qty" value="1"
                                               min="0" step="1"/>
                                        <input type="button" class="plus" value="+"/>
                                    </div>
                                    </p>
                                </li>
                                <li><p>Giá : 100,000 VNĐ</p></li>
                            </ul>
                        </div>
                        <div class="clearfix"></div>

                    </div>
                </div>
                <div class="cart-header2">
                    <div class="close2"></div>
                    <div class="cart-sec simpleCart_shelfItem">
                        <div class="cart-item cyc">
                            <img src="/template/img/11.jpg" class="img-responsive" alt=""/>
                        </div>
                        <div class="cart-item-info">
                            <h3><a href="#">Mountain Hopper(XS R034)</a><span>Model No: 3578</span></h3>
                            <ul class="qty">
                                <li><p>Size : 5</p></li>
                                <li>
                                    <p>
                                        <div class="quantity buttons_added">Số lượng
                                            <input type="button" class="minus" value="-"/>
                                            <input type="number" size="4" class="input-text qty text" title="Qty" value="1"
                                                   min="0" step="1"/>
                                            <input type="button" class="plus" value="+"/>
                                        </div>
                                    </p>
                                </li>
                                <li><p>Giá : 100,000 VNĐ</p></li>
                            </ul>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 cart-total">
                <a class="continue" href="#"><i class="fa fa-buy"></i>TIẾP TỤC MUA HÀNG</a>
                <div class="price-details">
                    <h3>Chi tiết giá</h3>
                    <span>Tổng đơn hàng : </span>
                    <span class="total1">6200.00</span>
                    <span>Giảm giá : </span>
                    <span class="total1">---</span>
                    <span>Phí vận chuyển : </span>
                    <span class="total1">150.00</span>

                    <div class="clearfix"></div>
                </div>
                <ul class="total_price">
                    <li class="last_price"><h4>TỔNG CỘNG</h4></li>
                    <li class="last_price"><span>6350.00</span></li>
                    <div class="clearfix"></div>
                </ul>
                <div class="clearfix"></div>
                <a class="order" href="#"><i class="fa fa-money"></i>THANH TOÁN</a>

                <div class="total-item">
                    <div class="cpns" href="#" id="cpnsID">SỬ DỤNG MÃ GIẢM GIÁ</div>
                    <input type="text" id="coupons" placeholder="Nhập mã giảm giá" style="display:none"/>

                    <p><a href="register.html">Đăng nhập</a> để sử dụng tài khoản - phiếu giảm giá</p>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>