<div class="single-product-area">
    <div class="container" style="padding-left: 0px;padding-right: 0px;">
        <div class="row">
            <div class="col-md-12">
                <div class="product-bit-title">
                    <h2>
                        <div class="product-breadcroumb">
                            <a href="index.html">Trang chủ</a>
                            <a href="/san-pham">Giày xinh</a>
                            <a href="" class="active">3445 - BỆT VERSACE</a>
                        </div>
                    </h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="single-product-area">
    <div class="container">
        <div class="row">
            <div class="col-md-9 col-sm-12">
                <div class="single_left">
                    <div class="grid images_3_of_2">
                        <ul id="etalage">
                            <li>
                                    <img class="etalage_thumb_image" src="/template/img/10_1.jpg" class="img-responsive"/>
                                    <a href="/template/img/10_1.jpg" title="3445 - BỆT VERSACE"><img class="etalage_source_image" src="/template/img/10_1.jpg" class="img-responsive" title=""/></a>
                            </li>
                            <li>
                                <img class="etalage_thumb_image" src="/template/img/10_2.jpg" class="img-responsive"/>
                                <a href="/template/img/10_2.jpg" title="Caption for gallery item 1"><img class="etalage_source_image" src="/template/img/10_2.jpg" class="img-responsive" title=""/></a>
                            </li>
                            <li>
                                <img class="etalage_thumb_image" src="/template/img/11_1.jpg" class="img-responsive"/>
                                <a href="/template/img/11_1.jpg" title="Caption for gallery item 1"><img class="etalage_source_image" src="/template/img/11_1.jpg" class="img-responsive"/></a>
                            </li>
                            <li>
                                <img class="etalage_thumb_image" src="/template/img/11_4.jpg" class="img-responsive"/>
                                <a href="/template/img/11_4.jpg"><img class="etalage_source_image" src="/template/img/11_4.jpg" class="img-responsive"/></a>
                            </li>
							 <li>
                                <img class="etalage_thumb_image" src="/template/img/12_1.jpg" class="img-responsive"/>
                                <a href="/template/img/12_1.jpg"><img class="etalage_source_image" src="/template/img/12_1.jpg" class="img-responsive"/></a>
                            </li>
							 <li>
                                <img class="etalage_thumb_image" src="/template/img/12.jpg" class="img-responsive"/>
                                <a href="/template/img/12.jpg"><img class="etalage_source_image" src="/template/img/12.jpg" class="img-responsive"/></a>
                            </li>
                        </ul>
						<!--<div><button class="button-prev button1">Previous</button><button class="button-next button1">Next</button></div>-->
                        <div class="clearfix"></div>
                    </div>
                    <div class="desc1 span_3_of_2">
                        <h3>3445 - BỆT VERSACE</h3>
                        <span class="brand">Thương hiệu: <a href="#">NHT </a></span>
                        <br>
                        <span class="code">Mã sản phẩm: <pid>3445</pid></span>

                        <div class="line"></div>
                        <p>Hàng y hình, được xem hàng trước, được đổi trả trong vòng 30 ngày. Chất liệu nhung</p>

                        <div class="line"></div>
                        <div class="price">
                            <span class="price-new">150,000 VNĐ</span><br>
                            <span class="price-old">190,000 VNĐ</span> <br>
                            <!--<span class="price-tax">Ex Tax: $90.00</span><br>
                            <span class="points"><small>Price in reward points: 400</small></span><br>-->
                        </div>
                        <div class="line"></div>
                        <span class="text">Tình trạng : </span>
                        <span class="product-status">Còn hàng</span>

                        <div class="line"></div>
                        <div class="det_nav1">
                            <h4>Select a size</h4>

                            <div class=" sky-form col col-4">
                                <ul>
                                    <li><label class="checkbox"><input type="checkbox" name="checkbox"><i></i>L</label>
                                    </li>
                                    <li><label class="checkbox"><input type="checkbox" name="checkbox"><i></i>S</label>
                                    </li>
                                    <li><label class="checkbox"><input type="checkbox" name="checkbox"><i></i>M</label>
                                    </li>
                                    <li><label class="checkbox"><input type="checkbox" name="checkbox"><i></i>XL</label>
                                    </li>
                                </ul>
								
								<select class="dropdownlist">
								<option class="5">Đỏ</option>
								<option class="1">Vàng</option>
								<option class="3">Xám</option>
							</select>
                            </div>
                        </div>
                        <div class="line"></div>

                        <div class="btn_form quantity-buy-detail">
                            Số lượng <input type="number" size="4" class="input-text qty text" title="Qty" value="1"
                                            min="0" step="1">
                            <a class="add-to-cart" href="checkout.html"><i class="fa fa-shopping-cart"></i>Thêm vào giỏ
                                hàng</a>
                            <a class="buy-now" href="checkout.html"><i class="fa fa-check"></i>Mua ngay</a>
                        </div>

                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="single-bottom1">
                    <h6>Chi tiết</h6>

                    <p class="prod-desc"> ✓ Balô dây rút hàng Việt Nam xuất khẩu, chất lượng đảm bảo.<br>
                        ✓ Chất liệu simili 100% không thấm nước, không bong tróc. Bạn sẽ yên tâm đi mưa & dễ lau chùi
                        khi bị bẩn.<br>
                        ✓ Công nghệ in Nhật Bản cho hình in đẹp, đặc biệt mặt in còn được phủ lên lớp màng chống trầy
                        xước và phai màu nên bạn hoàn toàn yên tâm khi sử dụng.</p>
                </div>
                <div class="single-bottom2">
                    <h6>Related Products</h6>

                    <div class="product">
                        <div class="product-desc">
                            <div class="product-img">
                                <img src="/template/img/w8.jpg" class="img-responsive " alt=""/>
                            </div>
                            <div class="prod1-desc">
                                <h5><a class="cbp-vm-title" href="#">Excepteur sint</a></h5>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="product_price">
                            <span class="price-access"><ins>150,000 VNĐ</ins></span>
                            <button class="button1"><span><i class="fa fa-shopping-cart"></i>Thêm vào giỏ hàng</span>
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="product">
                        <div class="product-desc">
                            <div class="product-img">
                                <img src="/template/img/w10.jpg" class="img-responsive " alt=""/>
                            </div>
                            <div class="prod1-desc">
                                <h5><a class="product_link" href="#">Excepteur sint</a></h5>

                                <p class="product_descr"> Vivamus ante lorem, eleifend nec interdum non, ullamcorper et
                                    arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
                                    inceptos himenaeos. </p>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="product_price">
								<span class="price-access">
										<ins>150,000 VNĐ</ins>
										<del>300,000 VNĐ</del>
								</span>
                            <button class="button1"><span><i class="fa fa-shopping-cart"></i>Thêm vào giỏ hàng</span>
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
					<div class="product">
                        <div class="product-desc">
                            <div class="product-img">
                                <img src="/template/img/w10.jpg" class="img-responsive " alt=""/>
                            </div>
                            <div class="prod1-desc">
                                <h5><a class="product_link" href="#">Excepteur sint</a></h5>

                                <p class="product_descr"> Vivamus ante lorem, eleifend nec interdum non, ullamcorper et
                                    arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
                                    inceptos himenaeos. </p>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="product_price">
								<span class="price-access">
										<ins>150,000 VNĐ</ins>
										<del>300,000 VNĐ</del>
								</span>
                            <button class="button1"><span><i class="fa fa-shopping-cart"></i>Thêm vào giỏ hàng</span>
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
					<div class="product">
                        <div class="product-desc">
                            <div class="product-img">
                                <img src="/template/img/w10.jpg" class="img-responsive " alt=""/>
                            </div>
                            <div class="prod1-desc">
                                <h5><a class="product_link" href="#">Excepteur sint</a></h5>

                                <p class="product_descr"> Vivamus ante lorem, eleifend nec interdum non, ullamcorper et
                                    arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
                                    inceptos himenaeos. </p>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="product_price">
								<span class="price-access">
										<ins>150,000 VNĐ</ins>
										<del>300,000 VNĐ</del>
								</span>
                            <button class="button1"><span><i class="fa fa-shopping-cart"></i>Thêm vào giỏ hàng</span>
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
					<div class="product">
                        <div class="product-desc">
                            <div class="product-img">
                                <img src="/template/img/w10.jpg" class="img-responsive " alt=""/>
                            </div>
                            <div class="prod1-desc">
                                <h5><a class="product_link" href="#">Excepteur sint</a></h5>

                                <p class="product_descr"> Vivamus ante lorem, eleifend nec interdum non, ullamcorper et
                                    arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
                                    inceptos himenaeos. </p>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="product_price">
								<span class="price-access">
										<ins>150,000 VNĐ</ins>
										<del>300,000 VNĐ</del>
								</span>
                            <button class="button1"><span><i class="fa fa-shopping-cart"></i>Thêm vào giỏ hàng</span>
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-12">
                <div class="w_sidebar">
                    <div class="w_nav1">
                        <h4><a href="shop.html">Tất cả</a></h4>
                        <div id="cssmenu">
							<?php echo $category;?>
						</div>
                    </div>
                    <h3>Lọc theo</h3>
                    <section class="sky-form">
                        <h4>Danh mục</h4>

                        <div class="row1 scroll-pane scrollbox3">
                            <div class="col col-4">
                                <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>kurtas</label>
                            </div>
                            <div class="col col-4">
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>kutis</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>churidar
                                    kurta</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>salwar</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>printed
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                            </div>
                        </div>
                    </section>
                    <section class="sky-form">
                        <h4>Phong cách</h4>

                        <div class="row1 scroll-pane scrollbox3">
                            <div class="col col-4">
                                <label class="checkbox"><input type="checkbox" name="checkbox"
                                                               checked=""><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                            </div>
                            <div class="col col-4">
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>vishud</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>amari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                            </div>
                        </div>
                    </section>
                    <section class="sky-form">
                        <h4>Màu sắc</h4>
                        <ul class="w_nav2 scrollbox3">
                            <li><a class="color1" href="#"></a></li>
                            <li><a class="color2" href="#"></a></li>
                            <li><a class="color3" href="#"></a></li>
                            <li><a class="color4" href="#"></a></li>
                            <li><a class="color5" href="#"></a></li>
                            <li><a class="color6" href="#"></a></li>
                            <li><a class="color7" href="#"></a></li>
                            <li><a class="color8" href="#"></a></li>
                            <li><a class="color9" href="#"></a></li>
                            <li><a class="color10" href="#"></a></li>
                            <li><a class="color12" href="#"></a></li>
                            <li><a class="color13" href="#"></a></li>
                            <li><a class="color14" href="#"></a></li>
                            <li><a class="color15" href="#"></a></li>
                            <li><a class="color5" href="#"></a></li>
                            <li><a class="color6" href="#"></a></li>
                            <li><a class="color7" href="#"></a></li>
                            <li><a class="color8" href="#"></a></li>
                            <li><a class="color9" href="#"></a></li>
                            <li><a class="color10" href="#"></a></li>
                        </ul>
                    </section>
                    <section class="sky-form">
                        <h4>Giảm giá</h4>

                        <div class="row1 scroll-pane scrollbox3">
                            <div class="col col-4">
                                <label class="radio"><input type="radio" name="radio" checked=""><i></i>60 % and
                                    above</label>
                                <label class="radio"><input type="radio" name="radio"><i></i>50 % and above</label>
                                <label class="radio"><input type="radio" name="radio"><i></i>40 % and above</label>
                            </div>
                            <div class="col col-4">
                                <label class="radio"><input type="radio" name="radio"><i></i>30 % and above</label>
                                <label class="radio"><input type="radio" name="radio"><i></i>20 % and above</label>
                                <label class="radio"><input type="radio" name="radio"><i></i>10 % and above</label>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>