<div class="single-product-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="product-bit-title">
                    <h2>
                        <div class="product-breadcroumb">
                           <?=$urlCategory;?>
						   <a class="active"><?=$productDetail[0]['PRODUCT']['PRODUCT_NAME'];?></a>
                        </div>
                    </h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="single-product-area">
    <div class="container">
        <div class="row">
            <div class="col-md-9 col-sm-12">
                <div class="single_left">
                    <div class="grid images_3_of_2">
                        <ul id="etalage">
							<?php
								$img=split('@@@',$productDetail[0]['PRODUCT']['SMALL_IMAGE_URL']);
								if(count($img>0)){
								unset($img[0]);
								if(count($arrayImage)>0)
									$img=$arrayImage;
								foreach($img as $k=>$image){
							?>
                            <li>
									<img class="etalage_thumb_image" src="/public/product/<?=$productDetail[0]['PRODUCT']['PRODUCT_ID'];?>/medium/<?=$image;?>" class="img-responsive" alt="">
                                    <a href="/public/product/<?=$productDetail[0]['PRODUCT']['PRODUCT_ID'];?>/medium/<?=$image;?>" title="<?=mb_strtoupper($productDetail[0]['PRODUCT']['PRODUCT_NAME'],'utf-8');?>">
									<img class="etalage_source_image" src="/public/product/<?=$productDetail[0]['PRODUCT']['PRODUCT_ID'];?>/medium/<?=$image;?>" class="img-responsive" title=""/>
									</a>
                            </li>
							<?php }}?>
                        </ul>
						<!--<div><button class="button-prev button1">Previous</button><button class="button-next button1">Next</button></div>-->
                        <div class="clearfix"></div>
                    </div>
                    <div class="desc1 span_3_of_2">
                        <h3><?=mb_strtoupper($productDetail[0]['PRODUCT']['PRODUCT_NAME'],'utf-8');?></h3>
                        <!--<span class="brand">Thương hiệu: <a href="#">NHT </a></span>-->
                        <span class="code">Mã sản phẩm: <pid><?=$productDetail[0]['PRODUCT']['MANUFACTURER_PARTY_ID'];?></pid></span>
                        <?=($productDetail[0]['PRODUCT']['DESCRIPTION']!='')?'<div class="line"></div><p>'.$productDetail[0]['PRODUCT']['DESCRIPTION'].'</p>':'';?>
                        <div class="line"></div>
                        <div id="price" class="price">
							<?php if($priceSale>0){?>
												<span class="price-new"><?=number_format($priceSale);?> VNĐ</span><br>
												<span class="price-old"><?=number_format($priceDefault);?> VNĐ</span>
											<?php }else{?>
												<span class="price-new"><?=number_format($priceDefault);?> VNĐ</span>
											<?php }?>
                            <!--<span class="price-tax">Ex Tax: $90.00</span><br>
                            <span class="points"><small>Price in reward points: 400</small></span><br>-->
                        </div>
                        <div class="line"></div>
						
                        <span class="text">Tình trạng : </span>
                        <span class="product-status">Còn hàng </span>
						<?php if(count($arrayFeature['listFeatureType'])>0){?>
                        <div class="line"></div>
                        <div class="det_nav1">
							<?php foreach($arrayFeature['listFeatureType'] as $k=>$featureType){?>
                            <h4>CHỌN <?=$featureType['DESCRIPTION_FEATURE_TYPE'];?></h4>
							<div class="clearfix"></div>
                            <div class=" sky-form col col-4">
								<select onchange="getProductFeature();" id="<?=$featureType['PRODUCT_FEATURE_TYPE_ID'];?>" class="dropdownlist wide">
								<?php $firt=1; foreach($arrayFeature['listFeature'][$k] as $k1=>$feature){
									$t=0;
									$t=$firt;
									$style='';
									if($feature['COMMENT']!='')
										$style='data-style="'.$feature['COMMENT'].'"';
									if($select==$feature['PRODUCT_FEATURE_ID']){
								?>
									<option <?=$style;?> selected <?php if(in_array($featureType['PRODUCT_FEATURE_TYPE_ID'],$TYPE_SHOW_IMAGE)){$showImg=$t;?>findShow="<?=($k1==0)?1:$t;?>" <?php }?> value="<?=$feature['PRODUCT_FEATURE_ID'];?>"><?=mb_strtoupper($feature['DESCRIPTION_FEATURE'],'utf-8');?></option>
								<?php }else{?>
									<option <?=$style;?> <?php if(in_array($featureType['PRODUCT_FEATURE_TYPE_ID'],$TYPE_SHOW_IMAGE)){?>findShow="<?=($k1==0)?1:$t;?>" <?php }?> value="<?=$feature['PRODUCT_FEATURE_ID'];?>"><?=mb_strtoupper($feature['DESCRIPTION_FEATURE'],'utf-8');?></option>
								<?php }
									$firt=coutImage($productJunior,$feature['PRODUCT_FEATURE_ID'])+$t;
								}?>
							</select>
							<div class="clearfix"></div>
                            </div>
							<?php }?>
                        </div>
						<?php }?>
						
                        <div class="line"></div>
                        <div class="btn_form quantity-buy-detail">
                            <span class="txtcssQt">Số lượng</span> <input onblur="checkEmptyToOneDetail('qty')" type="number" name="qty" id="qty" size="4" class="input-text qty text" title="Số lượng" value="1"
                                            min="1" step="1">
                            <button title="Thêm vào giỏ hàng" class="add-to-cart" href="#"><i class="fa fa-shopping-cart"></i>Thêm vào giỏ
                                hàng</button>
                            <a title="Mua sản phẩm" class="buy-now" id="buyNow" href="#"><i class="fa fa-check"></i>Mua ngay</a>
                        </div>

                    </div>
					
                    <div class="clearfix"></div>
                </div>
                <div class="single-bottom1">
                    <h6>Chi tiết</h6>
                    <p class="prod-desc"><?=$productDetail[0]['PRODUCT']['LONG_DESCRIPTION'];?></p>
                </div>
				<?php 
				if(count($listProductRelatedFinal)>0){
				?>
                <div class="single-bottom2">
                    <h6>Related Products</h6>
					<?php foreach($listProductRelatedFinal as $k=>$product){
							$img=split('@@@',$product['SMALL_IMAGE_URL']);
							$imgName='';
							if(count($img>0))
								$imgName=$img[1];
						?>
                    <div class="product">
                        <div class="product-desc">
                            <div class="product-img">
								<img src="/public/product/<?=$product['PRODUCT_ID'];?>/medium/<?=$imgName;?>" class="img-responsive " alt="<?=$product['PRODUCT_NAME'];?>">
                            </div>
                            <div class="prod1-desc">
                                <h5><a class="product_link" title="<?=$product['PRODUCT_NAME'];?>" href="<?=$product['URL'];?>/<?=convertStringAndId($product['PRODUCT_NAME'],$product['PRODUCT_ID'],'.html');?>"><?=$product['PRODUCT_NAME'];?></a></h5>
                                <p class="product_descr"><?=$product['DESCRIPTION'];?></p>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="product_price">
								<span class="price-access">
										<?php if($product['PRODUCT_PRICE_S']>0){?>
												<ins><?=number_format($product['PRODUCT_PRICE_S']);?> VNĐ</ins>
												<del><?=number_format($product['PRODUCT_PRICE_D']);?> VNĐ</del>
											<?php }else{?>
												<ins><?=number_format($product['PRODUCT_PRICE_D']);?> VNĐ</ins>
											<?php }?>
								</span>
                            <button class="button1" onclick="javascript:location.href='<?=$product['URL'];?>/<?=convertStringAndId($product['PRODUCT_NAME'],$product['PRODUCT_ID'],'.html');?>'"><span><i class="fa fa-shopping-cart"></i>Thêm vào giỏ hàng</span>
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
					<?php }?>
                </div>
				<?php }?>
            </div>
            <div class="col-md-3 col-sm-12">
                <div class="w_sidebar">
                    <div class="w_nav1">
                        <h4><a href="shop.html">Tất cả</a></h4>
                        <div id="cssmenu">
							<?php echo $category;?>
						</div>
                    </div>
					<?php
					if(count($listProductHot)>0){
					?>
                    <section class="sky-form">
                        <h4>Bán chạy</h4>
                        <div class="row1 scroll-pane scrollbox3">
							<div class="single-sidebar">
								<?php foreach($listProductHot as $k=>$product){
									$img=split('@@@',$product['SMALL_IMAGE_URL']);
									$imgName='';
									if(count($img>0))
										$imgName=$img[1];
								?>
									<div class="thubmnail-recent">
										<img src="/public/product/<?=$product['PRODUCT_ID'];?>/medium/<?=$imgName;?>" class="recent-thumb" alt="<?=$product['PRODUCT_NAME'];?>">
										<h2><a title="<?=$product['PRODUCT_NAME'];?>" href="<?=$product['URL'];?>/<?=convertStringAndId($product['PRODUCT_NAME'],$product['PRODUCT_ID'],'.html');?>"><?=$product['PRODUCT_NAME'];?></a></h2>
										<div class="product-sidebar-price">
											<?php if($product['PRODUCT_PRICE_S']>0){?>
												<ins><?=number_format($product['PRODUCT_PRICE_S']);?> VNĐ</ins>
												<del><?=number_format($product['PRODUCT_PRICE_D']);?> VNĐ</del>
											<?php }else{?>
												<ins><?=number_format($product['PRODUCT_PRICE_D']);?> VNĐ</ins>
											<?php }?>
										</div>                             
									</div>
								<?php }?>
							</div>
                        </div>
                    </section>
					<?php }?>
                    <section class="sky-form">
                        <h4>TAGS</h4>
                            <ul class="w_nav_tags scrollbox3">
                            <li><a href="#">Sản phẩm hot</a></li>
                            <li><a href="#">Búp bê</a></li>
                            <li><a href="#">Cao gót</a></li>
                            <li><a href="#">Sandal</a></li>
							<li><a href="#">Búp bê</a></li>
                            <li><a href="#">Cao gót</a></li>
                            <li><a href="#">Sandal</a></li>
                        </ul>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>