<div class="single-product-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="product-bit-title">
                    <h2>
                        <div class="product-breadcroumb">
                            <?=$urlCategory;?>
                        </div>
                    </h2>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="single-product-area">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-3">
                <div class="w_sidebar">
                    <div class="w_nav1">
						<h4>DANH MỤC</h4>
                        <div id="cssmenu">
							<?php echo $category;?>
						</div>
                    </div>
					<?php
					if(count($arrayCategoryFilter)>0){
					?>
                    <h3>Lọc theo</h3>
                    <section class="sky-form">
						
                        <h4><?=$arrayNameFilter[0]['NAME']?></h4>
                        <div class="row1 scroll-pane scrollbox3">
                            <div class="col col-4">
                                <label class="radio"><input type="radio" name="filter_type1" value="0"><i></i>TẤT CẢ</label>
								<?php
									foreach ($arrayValueFilter[0] as $k1 => $v1) {
								?>
									<label class="radio"><input type="radio" name="filter_type1" value="<?=$v1['MENU_ID'];?>"><i></i><?=mb_strtoupper($v1['NAME'],'utf-8');?></label>
								<?php }?>
                            </div>
                        </div>
                    </section>
					
                    <section class="sky-form">
                        <h4><?=$arrayNameFilter[1]['NAME']?></h4>
						<input type="hidden" value="-1" id="idColor"/>
                        <ul id="filterColor" class="w_nav2 scrollbox3">
							<?php
								foreach ($arrayValueFilter[1] as $k1 => $v1) {
									$colorarr=explode('#',$v1['URL']);
									$color='';
									if(isset($colorarr[1]))
										$color=$colorarr[1];
							?>
									<li><span title="<?=$v1['NAME'];?>" id="<?=$v1['MENU_ID'];?>" style="background:#<?=$color;?>;" onclick="filterColor(<?=$v1['MENU_ID'];?>);"></span></li>
							<?php }?>
                        </ul>
                    </section>
					<?php }?>
                    <section class="sky-form">
                        <h4>TAGS</h4>
                            <ul class="w_nav_tags scrollbox3">
                            <li><a href="#">Sản phẩm hot</a></li>
                            <li><a href="#">Búp bê</a></li>
                            <li><a href="#">Cao gót</a></li>
                            <li><a href="#">Sandal</a></li>
							<li><a href="#">Búp bê</a></li>
                            <li><a href="#">Cao gót</a></li>
                            <li><a href="#">Sandal</a></li>
                        </ul>
                    </section>
                </div>
            </div>
			
            <div class="col-md-9 col-sm-9">
				<?php if(count($listProduct)>0){
					$delay=0.0;
				?>
                <div id="cbp-vm" class="cbp-vm-switcher cbp-vm-view-grid">
                    <div class="cbp-vm-options"><span>Xem theo</span>
                        <a id="grid" href="#" class="cbp-vm-icon cbp-vm-grid" data-view="cbp-vm-view-grid">Grid View</a>
                        <a id="list" href="#" class="cbp-vm-icon cbp-vm-list" data-view="cbp-vm-view-list">List View</a>
                        <div class="sort">
						<div id="slider-container"></div>
						Giá từ: <input type="text" id="amount" style="width: 170px;margin-top: 2px;padding:0;border: 0; color: #c228a6; font-weight: bold;font-size:12px;background: white;" disabled />
						Sắp xếp <select id="SORT">
                                <option value="DEFAULT" selected="selected">Mặc định</option>
                                <option value="SORT_NAME_DECREASE">Tên A-Z</option>
                                <option value="SORT_NAME_INCREASE">Tên Z-A</option>
                                <option value="SORT_PRICE_INCREASE">Giá tăng dần</option>
                                <option value="SORT_PRICE_DECREASE">Giá giảm dần</option>
                            </select>
							Hiển thị <select id="VIEWBY">
                                <option value="20">20</option>
                                <option value="30">30</option>
                                <option value="40">40</option>
                                <option value="50">50</option>
                            </select>
							</div>
                    </div>

                    <div class="line_product"></div>
                    <div class="clearfix"></div>
					
                    <ul id="listProductByCategory">
						<?php foreach($listProduct as $k=>$product){
							$img=split('@@@',$product['SMALL_IMAGE_URL']);
							$imgName='';
							if(count($img>0))
								$imgName=$img[1];
						?>
                        <li class="wow fadeIn animated" data-price="<?=($product['PRODUCT_PRICE_S']>0)?$product['PRODUCT_PRICE_S']:$product['PRODUCT_PRICE_D'];?>" data-wow-delay="<?=$delay;?>s">
                            <div class="cbp-vm-image"><a title="<?=$product['PRODUCT_NAME'];?>" href="<?=$product['URL'];?>/<?=convertStringAndId($product['PRODUCT_NAME'],$product['PRODUCT_ID'],'.html');?>">
							<img src="/public/product/<?=$product['PRODUCT_ID'];?>/medium/<?=$imgName;?>" alt="<?=$product['PRODUCT_NAME'];?>"></a>
                            </div>
                            <div></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a title="<?=$product['PRODUCT_NAME'];?>" href="<?=$product['URL'];?>/<?=convertStringAndId($product['PRODUCT_NAME'],$product['PRODUCT_ID'],'.html');?>"><?=cut_string($product['PRODUCT_NAME'],18);?></a>
                                </div>
								<div class="list-title">
                                    <a title="<?=$product['PRODUCT_NAME'];?>" href="<?=$product['URL'];?>/<?=convertStringAndId($product['PRODUCT_NAME'],$product['PRODUCT_ID'],'.html');?>"><?=$product['PRODUCT_NAME'];?></a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                   <?php if($product['PRODUCT_PRICE_S']>0){?>
												<ins><?=number_format($product['PRODUCT_PRICE_S']);?> VNĐ</ins>
												<del><?=number_format($product['PRODUCT_PRICE_D']);?> VNĐ</del>
											<?php }else{?>
												<ins><?=number_format($product['PRODUCT_PRICE_D']);?> VNĐ</ins>
											<?php }?>
                                </div>
                                <div class="clearfix"></div>
								<?php if($product['DESCRIPTION']!=''&&$product['DESCRIPTION']!=null){?>
									<div class="cbp-vm-details "><?=$product['DESCRIPTION'];?></div>
								<?php }?>
                                <div class="clearfix"></div>
                                <div><a onclick="showProduct(<?=$product['PRODUCT_ID']?>);" class="cbp-vm-icon cbp-vm-add item_add">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
							<?php
								if($k<count($listProduct)-1){
							?>
                            <div class="lineListView"></div>
							<?php }?>
                        </li>
						<?php $delay=$delay+0.1;}?>
                    </ul>
                </div>
				<?php }else {echo "Danh mục đang cập nhật sản phẩm";}?>
				<?php if(count($listProduct)>0){?>
                <div class="row">
                    <div class="col-md-12" id="pagination">
                        <div id="more">Xem thêm sản phẩm</div>
                    </div>
                </div>
				<?php }?>
            </div>
        </div>
    </div>
</div>