<div class="single-product-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="product-bit-title">
                    <h2>
                        <div class="product-breadcroumb">
                            <a href="./">Trang chủ</a>
                            <a href="./san-pham">Sản phẩm</a>
                        </div>
                    </h2>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="single-product-area">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-3">
                <div class="w_sidebar">
                    <div class="w_nav1">
						<h4><a href="shop.html">Tất cả</a></h4>
                        <div id="cssmenu">
							<?php echo $category;?>
						</div>
                    </div>
                    <h3>Lọc theo</h3>
                    <section class="sky-form">
                        <h4>Danh mục</h4>

                        <div class="row1 scroll-pane scrollbox3">
                            <div class="col col-4">
                                <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>kurtas</label>
                            </div>
                            <div class="col col-4">
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>kutis</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>churidar
                                    kurta</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>salwar</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>printed
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>fashion
                                    sari</label>
                            </div>
                        </div>
                    </section>
                    <section class="sky-form">
                        <h4>Phong cách</h4>

                        <div class="row1 scroll-pane scrollbox3">
                            <div class="col col-4">
                                <label class="checkbox"><input type="checkbox" name="checkbox"
                                                               checked=""><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                            </div>
                            <div class="col col-4">
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>vishud</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>amari</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>shree</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Anouk</label>
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>biba</label>
                            </div>
                        </div>
                    </section>
                    <section class="sky-form">
                        <h4>màu sắc</h4>
                        <ul class="w_nav2 scrollbox3">
                            <li><a class="color1" href="#"></a></li>
                            <li><a class="color2" href="#"></a></li>
                            <li><a class="color3" href="#"></a></li>
                            <li><a class="color4" href="#"></a></li>
                            <li><a class="color5" href="#"></a></li>
                            <li><a class="color6" href="#"></a></li>
                            <li><a class="color7" href="#"></a></li>
                            <li><a class="color8" href="#"></a></li>
                            <li><a class="color9" href="#"></a></li>
                            <li><a class="color10" href="#"></a></li>
                            <li><a class="color12" href="#"></a></li>
                            <li><a class="color13" href="#"></a></li>
                            <li><a class="color14" href="#"></a></li>
                            <li><a class="color15" href="#"></a></li>
                            <li><a class="color5" href="#"></a></li>
                            <li><a class="color6" href="#"></a></li>
                            <li><a class="color7" href="#"></a></li>
                            <li><a class="color8" href="#"></a></li>
                            <li><a class="color9" href="#"></a></li>
                            <li><a class="color10" href="#"></a></li>
                        </ul>
                    </section>
                    <section class="sky-form">
                        <h4>giảm giá</h4>

                        <div class="row1 scroll-pane scrollbox3">
                            <div class="col col-4">
                                <label class="radio"><input type="radio" name="radio" checked=""><i></i>60 % and
                                    above</label>
                                <label class="radio"><input type="radio" name="radio"><i></i>50 % and above</label>
                                <label class="radio"><input type="radio" name="radio"><i></i>40 % and above</label>
                            </div>
                            <div class="col col-4">
                                <label class="radio"><input type="radio" name="radio"><i></i>30 % and above</label>
                                <label class="radio"><input type="radio" name="radio"><i></i>20 % and above</label>
                                <label class="radio"><input type="radio" name="radio"><i></i>10 % and above</label>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
            <div class="col-md-9 col-sm-9">
                <div id="cbp-vm" class="cbp-vm-switcher cbp-vm-view-grid">
                    <div class="cbp-vm-options"><span>Xem theo</span>
                        <a id="grid" href="#" class="cbp-vm-icon cbp-vm-grid" data-view="cbp-vm-view-grid">Grid View</a>
                        <a id="list" href="#" class="cbp-vm-icon cbp-vm-list" data-view="cbp-vm-view-list">List View</a>

                        <div class="sort">Sắp xếp <select>
                                <option value="DEFAULT" selected="selected">Mặc định</option>
                                <option value="SORT_NAME_DECREASE">Tên A-Z</option>
                                <option value="SORT_NAME_INCREASE">Tên Z-A</option>
                                <option value="SORT_PRICE_INCREASE">Giá tăng dần</option>
                                <option value="SORT_PRICE_DECREASE">Giá giảm dần</option>
                            </select></div>
                    </div>

                    <div class="line_product"></div>
                    <div class="clearfix"></div>
                    <ul>
                        <li class="wow fadeIn animated" data-wow-delay="0.0s">
                            <div class="cbp-vm-image"><a href="./san-pham/3445 - BỆT VERSACE"><img
                                        src="/template/img/bdff114_master.jpg" class="img-responsive" alt=""/></a>
                            </div>
                            <div></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a href="./san-pham/3445 - BỆT VERSACE">3445 - BỆT VERSACE</a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                    <ins>150,000 VNĐ</ins>
                                </div>
                                <div class="clearfix"></div>

                                <div class="clearfix"></div>
                                <div><a class="cbp-vm-icon cbp-vm-add item_add" href="#">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
                            <div class="lineListView"></div>
                        </li>
                        <li class="wow fadeIn animated" data-wow-delay="0.1s">
                            <div class="cbp-vm-image"><a href="single.html"><img src="/template/img/p1.jpg"
                                                                                 class="img-responsive"
                                                                                 alt=""/></a></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a href="single.html">3445 - BỆT VERSACE</a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                    <ins>150,000 VNĐ</ins>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-details">
                                    Silver beet shallot wakame tomatillo salsify mung bean beetroot groundnut.
                                </div>
                                <div class="clearfix"></div>
                                <div><a class="cbp-vm-icon cbp-vm-add item_add" href="#">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
                            <div class="lineListView"></div>
                        </li>
                        <li class="wow fadeIn animated" data-wow-delay="0.1s">
                            <div class="cbp-vm-image"><a href="single.html"><img src="/template/img/p1.jpg"
                                                                                 class="img-responsive"
                                                                                 alt=""/></a></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a href="single.html">3445 - BỆT VERSACE</a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                    <ins>150,000 VNĐ</ins>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-details">
                                    Silver beet shallot wakame tomatillo salsify mung bean beetroot groundnut.
                                </div>
                                <div class="clearfix"></div>
                                <div><a class="cbp-vm-icon cbp-vm-add item_add" href="#">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
                            <div class="lineListView"></div>
                        </li>
                        <li class="wow fadeIn animated" data-wow-delay="0.1s">
                            <div class="cbp-vm-image"><a href="single.html"><img src="/template/img/p1.jpg"
                                                                                 class="img-responsive"
                                                                                 alt=""/></a></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a href="single.html">3445 - BỆT VERSACE</a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                    <ins>150,000 VNĐ</ins>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-details">
                                    Silver beet shallot wakame tomatillo salsify mung bean beetroot groundnut.
                                </div>
                                <div class="clearfix"></div>
                                <div><a class="cbp-vm-icon cbp-vm-add item_add" href="#">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
                            <div class="lineListView"></div>
                        </li>
                        <li class="wow fadeIn animated" data-wow-delay="0.1s">
                            <div class="cbp-vm-image"><a href="single.html"><img src="/template/img/p1.jpg"
                                                                                 class="img-responsive"
                                                                                 alt=""/></a></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a href="single.html">3445 - BỆT VERSACE</a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                    <ins>150,000 VNĐ</ins>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-details">
                                    Silver beet shallot wakame tomatillo salsify mung bean beetroot groundnut.
                                </div>
                                <div class="clearfix"></div>
                                <div><a class="cbp-vm-icon cbp-vm-add item_add" href="#">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
                            <div class="lineListView"></div>
                        </li>
                        <li class="wow fadeIn animated" data-wow-delay="0.1s">
                            <div class="cbp-vm-image"><a href="single.html"><img src="/template/img/p1.jpg"
                                                                                 class="img-responsive"
                                                                                 alt=""/></a></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a href="single.html">3445 - BỆT VERSACE</a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                    <ins>150,000 VNĐ</ins>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-details">
                                    Silver beet shallot wakame tomatillo salsify mung bean beetroot groundnut.
                                </div>
                                <div class="clearfix"></div>
                                <div><a class="cbp-vm-icon cbp-vm-add item_add" href="#">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
                            <div class="lineListView"></div>
                        </li>
                        <li class="wow fadeIn animated" data-wow-delay="0.2s">
                            <div class="cbp-vm-image"><a href="single.html"><img src="/template/img/p2.jpg"
                                                                                 class="img-responsive"
                                                                                 alt=""/></a></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a href="single.html">3445 - BỆT VERSACE</a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                    <ins>150,000 VNĐ</ins>
                                    <del>300,000 VNĐ</del>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-details">
                                    Silver beet shallot wakame tomatillo salsify mung bean beetroot groundnut.
                                </div>
                                <div class="clearfix"></div>
                                <div><a class="cbp-vm-icon cbp-vm-add item_add" href="#">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
                            <div class="lineListView"></div>
                        </li>
                        <li class="wow fadeIn animated" data-wow-delay="0.3s">
                            <div class="cbp-vm-image"><a href="single.html"><img src="/template/img/p3.jpg"
                                                                                 class="img-responsive"
                                                                                 alt=""/></a></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a href="single.html">3445 - BỆT VERSACE</a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                    <ins>150,000 VNĐ</ins>
                                    <del>300,000 VNĐ</del>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-details">
                                    Silver beet shallot wakame tomatillo salsify mung bean beetroot groundnut.
                                </div>
                                <div class="clearfix"></div>
                                <div><a class="cbp-vm-icon cbp-vm-add item_add" href="#">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
                            <div class="lineListView"></div>
                        </li>
                        <li class="wow fadeIn animated" data-wow-delay="0.4s">
                            <div class="cbp-vm-image"><a href="single.html"><img src="/template/img/p4.jpg"
                                                                                 class="img-responsive"
                                                                                 alt=""/></a></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a href="single.html">3445 - BỆT VERSACE</a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                    <ins>150,000 VNĐ</ins>
                                    <del>300,000 VNĐ</del>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-details">
                                    Silver beet shallot wakame tomatillo salsify mung bean beetroot groundnut.
                                </div>
                                <div class="clearfix"></div>
                                <div><a class="cbp-vm-icon cbp-vm-add item_add" href="#">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
                            <div class="lineListView"></div>
                        </li>
                        <li class="wow fadeIn animated" data-wow-delay="0.5s">
                            <div class="cbp-vm-image"><a href="single.html"><img src="/template/img/p2.jpg"
                                                                                 class="img-responsive"
                                                                                 alt=""/></a></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a href="single.html">3445 - BỆT VERSACE</a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                    <ins>150,000 VNĐ</ins>
                                    <del>300,000 VNĐ</del>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-details">
                                    Silver beet shallot wakame tomatillo salsify mung bean beetroot groundnut.
                                </div>
                                <div class="clearfix"></div>
                                <div><a class="cbp-vm-icon cbp-vm-add item_add" href="#">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
                            <div class="lineListView"></div>
                        </li>
                        <li class="wow fadeIn animated" data-wow-delay="0.6s">
                            <div class="cbp-vm-image"><a href="single.html"><img src="/template/img/p1.jpg"
                                                                                 class="img-responsive"
                                                                                 alt=""/></a></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a href="single.html">3445 - BỆT VERSACE</a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                    <ins>150,000 VNĐ</ins>
                                    <del>300,000 VNĐ</del>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-details">
                                    Silver beet shallot wakame tomatillo salsify mung bean beetroot groundnut.
                                </div>
                                <div class="clearfix"></div>
                                <div><a class="cbp-vm-icon cbp-vm-add item_add" href="#">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
                            <div class="lineListView"></div>
                        </li>
                        <li class="wow fadeIn animated" data-wow-delay="0.7s">
                            <div class="cbp-vm-image"><a href="single.html"><img src="/template/img/p3.jpg"
                                                                                 class="img-responsive"
                                                                                 alt=""/></a></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a href="single.html">3445 - BỆT VERSACE</a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                    <ins>150,000 VNĐ</ins>
                                    <del>300,000 VNĐ</del>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-details">
                                    Silver beet shallot wakame tomatillo salsify mung bean beetroot groundnut.
                                </div>
                                <div class="clearfix"></div>
                                <div><a class="cbp-vm-icon cbp-vm-add item_add" href="#">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
                            <div class="lineListView"></div>
                        </li>
                        <li class="wow fadeIn animated" data-wow-delay="0.8s">
                            <div class="cbp-vm-image"><a href="single.html"><img src="/template/img/p3.jpg"
                                                                                 class="img-responsive"
                                                                                 alt=""/></a></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a href="single.html">3445 - BỆT VERSACE</a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                    <ins>150,000 VNĐ</ins>
                                    <del>300,000 VNĐ</del>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-details">
                                    Silver beet shallot wakame tomatillo salsify mung bean beetroot groundnut.
                                </div>
                                <div class="clearfix"></div>
                                <div><a class="cbp-vm-icon cbp-vm-add item_add" href="#">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
                            <div class="lineListView"></div>
                        </li>
                        <li class="wow fadeIn animated" data-wow-delay="0.9s">
                            <div class="cbp-vm-image"><a href="single.html"><img src="/template/img/p3.jpg"
                                                                                 class="img-responsive"
                                                                                 alt=""/></a></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a href="single.html">3445 - BỆT VERSACE</a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                    <ins>150,000 VNĐ</ins>
                                    <del>300,000 VNĐ</del>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-details">
                                    Silver beet shallot wakame tomatillo salsify mung bean beetroot groundnut.
                                </div>
                                <div class="clearfix"></div>
                                <div><a class="cbp-vm-icon cbp-vm-add item_add" href="#">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
                            <div class="lineListView"></div>
                        </li>
                        <li class="wow fadeIn animated" data-wow-delay="1s">
                            <div class="cbp-vm-image"><a href="single.html"><img src="/template/img/p3.jpg"
                                                                                 class="img-responsive"
                                                                                 alt=""/></a></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a href="single.html">3445 - BỆT VERSACE</a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                    <ins>150,000 VNĐ</ins>
                                    <del>300,000 VNĐ</del>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-details">
                                    Silver beet shallot wakame tomatillo salsify mung bean beetroot groundnut.
                                </div>
                                <div class="clearfix"></div>
                                <div><a class="cbp-vm-icon cbp-vm-add item_add" href="#">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
                            <div class="lineListView"></div>
                        </li>
                        <li class="wow fadeIn animated" data-wow-delay="1.1s">
                            <div class="cbp-vm-image"><a href="single.html"><img src="/template/img/p3.jpg"
                                                                                 class="img-responsive"
                                                                                 alt=""/></a></div>
                            <div class="product_container">
                                <div class="cbp-vm-title">
                                    <a href="single.html">3445 - BỆT VERSACE</a>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-price">
                                    <ins>150,000 VNĐ</ins>
                                    <del>300,000 VNĐ</del>
                                </div>
                                <div class="clearfix"></div>
                                <div class="cbp-vm-details">
                                    Silver beet shallot wakame tomatillo salsify mung bean beetroot groundnut.
                                </div>
                                <div class="clearfix"></div>
                                <div><a class="cbp-vm-icon cbp-vm-add item_add" href="#">THÊM VÀO GIỎ HÀNG</a></div>
                            </div>
                            <div class="lineListView"></div>
                        </li>

                    </ul>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="product-pagination text-center">
                            <nav>
                                <ul class="pagination">
                                    <li>
                                        <a href="#" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    </li>
                                    <li><a href="#">1</a></li>
                                    <li><a href="#">2</a></li>
                                    <li><a href="#">3</a></li>
                                    <li><a href="#">4</a></li>
                                    <li><a href="#">5</a></li>
                                    <li>
                                        <a href="#" aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>