<div class="product-widget-area">
    <div class="container" style="padding-left: 0px;padding-right: 0px;">
        <div class="main">
            <!-- start registration -->
            <div class="registration">
                <div class="registration_left">
                    <h2>TẠO MỚI TÀI KHOẢN</h2>

                    <div class="registration_form">
                        <!-- Form -->
                        <form id="registration_form" action="contact.php" method="post">
                            <div>
                                <label>
                                    <input placeholder="Họ" type="text" required autofocus>
                                </label>
                            </div>
                            <div>
                                <label>
                                    <input placeholder="Tên" type="text" required autofocus>
                                </label>
                            </div>
                            <div>
                                <label>
                                    <input placeholder="Email" type="email" required>
                                </label>
                            </div>
                            <div>
                                <label>
                                    <input placeholder="Địa chỉ" type="text" required>
                                </label>
                            </div>
                            <div>
                                <label>
                                    <input placeholder="Điện thoại" type="text" required>
                                </label>
                            </div>
                            <div class="sky-form">
                                <div class="sky_form1">
                                    <ul>
                                        <li><label class="radio left"><input type="radio" name="radio"
                                                                             checked=""><i></i>Nam</label></li>
                                        <li><label class="radio"><input type="radio" name="radio"><i></i>Nữ</label></li>
                                        <div class="clearfix"></div>
                                    </ul>
                                </div>
                            </div>
                            <div>
                                <label>
                                    <input placeholder="Mật khẩu" type="password" required>
                                </label>
                            </div>
                            <div>
                                <label>
                                    <input placeholder="Nhập lại mật khẩu" type="password" required>
                                </label>
                            </div>
                            <div class="sky-form">
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Tôi đồng ý điều
                                    khoản của LunShop &nbsp;<a class="terms" href="#"> Điều khoản</a> </label>
                            </div>
                            <div>
                                <input type="submit" value="Tạo tài khoản" id="register-submit">
                            </div>
                        </form>
                        <!-- /Form -->
                    </div>
                </div>
                <div class="registration_left">
                    <h2>ĐÃ CÓ TÀI KHOẢN</h2>

                    <div class="registration_form">
                        <!-- Form -->
                        <form id="registration_form" action="contact.php" method="post">
                            <div>
                                <label>
                                    <input placeholder="Email" type="email" tabindex="3" required>
                                </label>
                            </div>
                            <div>
                                <label>
                                    <input placeholder="Mật khẩu" type="password" tabindex="4" required>
                                </label>
                            </div>
                            <div>
                                <input type="submit" value="Đăng nhập" id="register-submit">
                            </div>
                            <div class="sky-form">
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Ghi nhớ đăng nhập</label>
                            </div>
                            <div class="forget">
                                <a href="#">Lấy lại mật khẩu</a>
                            </div>
                        </form>
                        <!-- /Form -->
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <!-- end registration -->
        </div>
    </div>
</div>