<div class="product-widget-area">
    <div class="container">
        <div class="contact">
            <div class="contact_info">
                <h2>CHỈ ĐƯỜNG</h2>

                <div class="map">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.649596787077!2d106.6158923148918!3d10.761465392331683!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752c255bdcd627%3A0x3ab65f8ba38bb74b!2zMTE0IOG6pHAgQ2hp4bq_biBMxrDhu6NjLCBCw6xuaCBUcuG7iyDEkMO0bmcsIELDrG5oIFTDom4sIEjhu5MgQ2jDrSBNaW5oLCBWaeG7h3QgTmFt!5e0!3m2!1svi!2s!4v1482213607269"
                            width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
                </div>
            </div>
            <div class="contact-form">
                <h2>LIÊN HỆ</h2>

                <form method="post" action="contact-post.html">
                    <div>
                        <span><label>Họ tên</label></span>
                        <span><input name="userName" type="text" class="textbox"></span>
                    </div>
                    <div>
                        <span><label>E-mail</label></span>
                        <span><input name="userEmail" type="text" class="textbox"></span>
                    </div>
                    <div>
                        <span><label>Điện thoại</label></span>
                        <span><input name="userPhone" type="text" class="textbox"></span>
                    </div>
                    <div>
                        <span><label>Nội dung</label></span>
                        <span><textarea name="userMsg"> </textarea></span>
                    </div>
                    <div>
                        <span><input type="submit" class="" value="Gửi "></span>
                    </div>
                </form>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>